In [51]:
import numpy as np
import pandas as pd

In [52]:
# Step 1: Load the dataset
import pickle
dataset = pd.read_pickle('dataset_final.pkl')

In [53]:
data = pd.read_pickle('wdSAW.pkl')
wdata = data.values

In [54]:
print(wdata)

[[0.15       0.15       0.03       0.06       0.015      0.1       ]
 [0.1875     0.1875     0.0375     0.075      0.015      0.1       ]
 [0.1875     0.15       0.03       0.075      0.01875    0.1       ]
 ...
 [0.1125     0.1125     0.03       0.075      0.015      0.08333333]
 [0.1125     0.1125     0.0225     0.075      0.015      0.08333333]
 [0.1875     0.1875     0.03       0.075      0.01875    0.16666667]]


In [55]:
impacts = ['-', '-', '-', '-', '-','-',]

In [56]:
# Step 6: Determine the ideal and negative-ideal solutions
ideal_solution = np.empty(6)
negative_ideal_solution = np.empty(6)

for i in range(6):
    if impacts[i] == '+':
        ideal_solution[i] = np.max(wdata[:, i])
        negative_ideal_solution[i] = np.min(wdata[:, i])
    else:
        ideal_solution[i] = np.min(wdata[:, i])
        negative_ideal_solution[i] = np.max(wdata[:, i])


print(ideal_solution)
print(negative_ideal_solution)

[0.1125  0.1125  0.0225  0.045   0.01125 0.05   ]
[0.25  0.25  0.075 0.15  0.075 0.2  ]


In [57]:
# Step 7: Calculate the Euclidean distances from the ideal and negative-ideal solutions
distance_to_ideal = np.sqrt(np.sum((wdata - ideal_solution) ** 2, axis=1))
distance_to_negative_ideal = np.sqrt(np.sum((wdata - negative_ideal_solution) ** 2, axis=1))

print(distance_to_ideal)
print(distance_to_negative_ideal)

[0.07488533 0.12202075 0.10268276 0.11330269 0.05524095 0.06405293
 0.07516648 0.06361232 0.12132729 0.03023347 0.03181981 0.18074499
 0.09877373 0.0799783  0.06405293 0.1024085  0.22465599 0.18689904
 0.06405293 0.06327986 0.10350121 0.03114984 0.24106534 0.10303047
 0.18689904 0.0921427  0.0911472  0.07864852 0.21918885 0.19206119
 0.06405293 0.11311637 0.21216518 0.10200167 0.19206119 0.06872474
 0.18255564 0.0782901  0.06327986 0.05352829 0.04816962 0.12132729
 0.10220826 0.18680287 0.06372276 0.06372276 0.10303047 0.10537713
 0.1032972  0.06372276 0.03092329 0.18689904 0.06104558 0.07864852
 0.07891627 0.06405293 0.01546165 0.12126933 0.0075     0.12109526
 0.         0.01718466 0.09122241 0.         0.19376613 0.10247713
 0.04816962 0.19239039 0.09122241 0.04107919 0.01546165 0.09934158
 0.06372276 0.09099088 0.10350121 0.01718466 0.06372276 0.18689904
 0.04038874 0.03       0.12150103 0.16733667 0.10268276 0.00375
 0.09905806 0.09972619 0.06405293 0.12132729 0.04056245 0.0640529

In [58]:
# Step 8: Calculate the relative closeness to the ideal solution
closeness = distance_to_negative_ideal / (distance_to_ideal + distance_to_negative_ideal)

print(closeness)

[0.7363105  0.58021372 0.64471677 0.60836152 0.81203915 0.77484879
 0.73460667 0.77764144 0.58421728 0.89892139 0.8934065  0.44844109
 0.6661     0.72586888 0.77484879 0.64771074 0.31130738 0.41792725
 0.77484879 0.77901002 0.64082944 0.89570187 0.29138936 0.65644106
 0.41792725 0.68953268 0.69139569 0.7314814  0.35630409 0.393299
 0.77484879 0.61041655 0.34795668 0.66171256 0.393299   0.77422482
 0.44034207 0.73392365 0.77901002 0.81669787 0.8394016  0.58421728
 0.66002519 0.41774601 0.77652501 0.77652501 0.65644106 0.65032731
 0.64274314 0.77652501 0.89668161 0.41792725 0.79268478 0.7314814
 0.72987369 0.77484879 0.94648105 0.58556064 0.97372596 0.58769614
 1.         0.94059568 0.69323916 1.         0.38357334 0.64660271
 0.8394016  0.39147647 0.69323916 0.86162349 0.94648105 0.66002481
 0.77652501 0.69486233 0.64082944 0.94059568 0.77652501 0.41792725
 0.86443465 0.89991211 0.58203246 0.48660896 0.64471677 0.98672501
 0.66284476 0.65935991 0.77484879 0.58421728 0.8635177  0.7748487

In [61]:
# Step 9: Rank the alternatives based on the relative closeness
ranked_indices = np.argsort(closeness)  # Sort in descending order

# Step 10: Print the ranked alternatives
for i, idx in enumerate(ranked_indices):
    print(f"Rank {i+1}: AlunoId {idx+1}")

Rank 1: AlunoId 259
Rank 2: AlunoId 496
Rank 3: AlunoId 113
Rank 4: AlunoId 248
Rank 5: AlunoId 800
Rank 6: AlunoId 292
Rank 7: AlunoId 492
Rank 8: AlunoId 112
Rank 9: AlunoId 540
Rank 10: AlunoId 446
Rank 11: AlunoId 281
Rank 12: AlunoId 500
Rank 13: AlunoId 361
Rank 14: AlunoId 493
Rank 15: AlunoId 170
Rank 16: AlunoId 250
Rank 17: AlunoId 163
Rank 18: AlunoId 814
Rank 19: AlunoId 114
Rank 20: AlunoId 544
Rank 21: AlunoId 542
Rank 22: AlunoId 488
Rank 23: AlunoId 762
Rank 24: AlunoId 436
Rank 25: AlunoId 467
Rank 26: AlunoId 444
Rank 27: AlunoId 561
Rank 28: AlunoId 249
Rank 29: AlunoId 382
Rank 30: AlunoId 468
Rank 31: AlunoId 497
Rank 32: AlunoId 23
Rank 33: AlunoId 350
Rank 34: AlunoId 453
Rank 35: AlunoId 336
Rank 36: AlunoId 348
Rank 37: AlunoId 399
Rank 38: AlunoId 721
Rank 39: AlunoId 365
Rank 40: AlunoId 353
Rank 41: AlunoId 808
Rank 42: AlunoId 167
Rank 43: AlunoId 188
Rank 44: AlunoId 699
Rank 45: AlunoId 358
Rank 46: AlunoId 494
Rank 47: AlunoId 363
Rank 48: AlunoId 454
Ra

In [60]:
print("[Nota Pt., Nota Mat., Autoaval., Notas, Envol.Score]")
print(dataset.iloc[495,:].values)
print(dataset.iloc[247,:].values)
print(dataset.iloc[258,:].values)
print(dataset.iloc[112,:].values)
print(dataset.iloc[491,:].values)
print(dataset.iloc[799,:].values)
print(dataset.iloc[111,:].values)

print("\nUltimas ranks - Alunos Baixo Risco")
print(dataset.iloc[63,:].values)
print(dataset.iloc[650,:].values)
print(dataset.iloc[60,:].values)
print(dataset.iloc[742,:].values)

[Nota Pt., Nota Mat., Autoaval., Notas, Envol.Score]
[ 2.  2.  2.  1. 12.  0.]
[ 2.  2.  2.  1. 16.  0.]
[ 2.  2.  1.  1. 18.  0.]
[ 2.  2.  2.  1. 17.  0.]
[ 2.  2.  2.  1. 18.  0.]
[ 2.  2.  2.  1. 18.  0.]
[ 2.  2.  3.  1. 17.  0.]

Ultimas ranks - Alunos Baixo Risco
[ 5.  5.  5.  5. 25.  3.]
[ 5.  5.  5.  5. 25.  3.]
[ 5.  5.  5.  5. 25.  3.]
[ 5.  5.  5.  5. 25.  3.]
