In [132]:
import pandas as pd
import numpy as np
import pandas as pd
import joblib
from sklearn.model_selection import cross_val_score
import numpy as np


In [133]:
# Step 1: Load the dataset

dataset = pd.read_pickle('dataset_final.pkl')

In [134]:
print(dataset)

     Q20__nota_português_2.ºperiodo  Q26__nota_mat_2.ºperiodo  \
0                               4.0                       4.0   
1                               3.0                       3.0   
2                               3.0                       4.0   
3                               3.0                       4.0   
4                               4.0                       4.0   
..                              ...                       ...   
840                             4.0                       2.0   
841                             3.0                       3.0   
842                             5.0                       5.0   
843                             5.0                       5.0   
844                             3.0                       3.0   

     Q16_satisfação_com_notas_escolares  Q15_as_minhas_notas  \
0                                   4.0                  4.0   
1                                   3.0                  3.0   
2                          

In [135]:
# Define the criteria weights
weights = [0.1, 0.1, 0.1, 0.1, 0.1, 0.5]  # Adjust the weights based on the importance of each feature

In [136]:
#features = dataset.values
#print(features)

In [137]:
range(len(dataset))

range(0, 845)

In [138]:
n_dataset= dataset.copy()

In [139]:
l = ['Q20__nota_português_2.ºperiodo','Q26__nota_mat_2.ºperiodo','Q16_satisfação_com_notas_escolares','Q15_as_minhas_notas','envolvimento_scoretotal', 'Prev_Cluster']

for nome in l:
    for indice, valor in n_dataset[nome].iteritems():
        # Faça alguma operação desejada com o valor da linha
        # Por exemplo, imprima o índice e o valor da linha
        if(nome=='Q20__nota_português_2.ºperiodo' or nome =='Q26__nota_mat_2.ºperiodo' or nome== 'Q16_satisfação_com_notas_escolares' or nome=='Q15_as_minhas_notas' or nome=='Prev_Cluster') :
            if(valor==0.0): 
                n_dataset.loc[indice,nome ]= 0.15
            if(valor==1.0): 
                n_dataset.loc[indice, nome]= 0.30
            if(valor==2.0): 
                n_dataset.loc[indice, nome]= 0.45
            if(valor==3.0): 
                n_dataset.loc[indice, nome]= 0.60
            if(valor==4.0): 
                n_dataset.loc[indice, nome]= 0.75
            if(valor==5.0): 
                n_dataset.loc[indice, nome ]= 1


        if(nome=='envolvimento_scoretotal'):   
           
            if(valor>=0.0 and valor<=5.0): 
                n_dataset.loc[indice, 'envolvimento_scoretotal']= 0.15
            if(valor>5.0 and valor<=10.0): 
                n_dataset.loc[indice, 'envolvimento_scoretotal']= 0.30
            if(valor>10.0 and valor<=15.0): 
                n_dataset.loc[indice, 'envolvimento_scoretotal']= 0.45
            if(valor>15.0 and valor<=20.0): 
                n_dataset.loc[indice, 'envolvimento_scoretotal']= 0.60
            if(valor>20.0 and valor<25.0): 
                n_dataset.loc[indice, 'envolvimento_scoretotal']= 0.75
            if(valor>=25.0): 
                n_dataset.loc[indice, 'envolvimento_scoretotal']= 1



In [140]:
min_values = n_dataset.min()

min_values

Q20__nota_português_2.ºperiodo        0.45
Q26__nota_mat_2.ºperiodo              0.45
Q16_satisfação_com_notas_escolares    0.30
Q15_as_minhas_notas                   0.30
envolvimento_scoretotal               0.15
Prev_Cluster                          0.15
dtype: float64

In [141]:
n_dataset

Q20__nota_português_2.ºperiodo  Q26__nota_mat_2.ºperiodo  \
0                              0.75                      0.75   
1                              0.60                      0.60   
2                              0.60                      0.75   
3                              0.60                      0.75   
4                              0.75                      0.75   
..                              ...                       ...   
840                            0.75                      0.45   
841                            0.60                      0.60   
842                            1.00                      1.00   
843                            1.00                      1.00   
844                            0.60                      0.60   

     Q16_satisfação_com_notas_escolares  Q15_as_minhas_notas  \
0                                  0.75                 0.75   
1                                  0.60                 0.60   
2                                  0.75                 0.60   
3                                  0.60                 0.45   
4                                  1.00                 0.75   
..                                  ...                  ...   
840                                0.60                 0.60   
841                                0.30                 0.30   
842                                0.75                 0.60   
843                                1.00                 0.60   
844                                0.75                 0.60   

     envolvimento_scoretotal  Prev_Cluster  
0                       0.75          0.30  
1                       0.75          0.30  
2                       0.60          0.30  
3                       0.60          0.30  
4                       0.75          0.60  
..                       ...           ...  
840                     0.60          0.45  
841                     0.60          0.15  
842                     0.75          0.60  
843                     0.75          0.60  
844                     0.60          0.30  

[845 rows x 6 columns]

In [142]:
normalized_data = n_dataset

In [143]:
l = ['Q20__nota_português_2.ºperiodo','Q26__nota_mat_2.ºperiodo','Q16_satisfação_com_notas_escolares','Q15_as_minhas_notas','envolvimento_scoretotal', 'Prev_Cluster']

for nome in l:
    for indice, valor in n_dataset[nome].iteritems():
        # Faça alguma operação desejada com o valor da linha
        # Por exemplo, imprima o índice e o valor da linha
        min_value = n_dataset[nome].min()

        valor = n_dataset.loc[indice, nome]
        normalized_data.loc[indice, nome]= min_value / valor
        

In [144]:
normalized_data

Q20__nota_português_2.ºperiodo  Q26__nota_mat_2.ºperiodo  \
0                              0.60                      0.60   
1                              0.75                      0.75   
2                              0.75                      0.60   
3                              0.75                      0.60   
4                              0.60                      0.60   
..                              ...                       ...   
840                            0.60                      1.00   
841                            0.75                      0.75   
842                            0.45                      0.45   
843                            0.45                      0.45   
844                            0.75                      0.75   

     Q16_satisfação_com_notas_escolares  Q15_as_minhas_notas  \
0                                   0.4             0.400000   
1                                   0.5             0.500000   
2                                   0.4             0.500000   
3                                   0.5             0.666667   
4                                   0.3             0.400000   
..                                  ...                  ...   
840                                 0.5             0.500000   
841                                 1.0             1.000000   
842                                 0.4             0.500000   
843                                 0.3             0.500000   
844                                 0.4             0.500000   

     envolvimento_scoretotal  Prev_Cluster  
0                       0.20      0.500000  
1                       0.20      0.500000  
2                       0.25      0.500000  
3                       0.25      0.500000  
4                       0.20      0.250000  
..                       ...           ...  
840                     0.25      0.333333  
841                     0.25      1.000000  
842                     0.20      0.416667  
843                     0.20      0.416667  
844                     0.25      0.833333  

[845 rows x 6 columns]

In [145]:
# Perform the SAW calculation
weighted_data = normalized_data * weights

weighted_data

Q20__nota_português_2.ºperiodo  Q26__nota_mat_2.ºperiodo  \
0                             0.060                     0.060   
1                             0.075                     0.075   
2                             0.075                     0.060   
3                             0.075                     0.060   
4                             0.060                     0.060   
..                              ...                       ...   
840                           0.060                     0.100   
841                           0.075                     0.075   
842                           0.045                     0.045   
843                           0.045                     0.045   
844                           0.075                     0.075   

     Q16_satisfação_com_notas_escolares  Q15_as_minhas_notas  \
0                                  0.04             0.040000   
1                                  0.05             0.050000   
2                                  0.04             0.050000   
3                                  0.05             0.066667   
4                                  0.03             0.040000   
..                                  ...                  ...   
840                                0.05             0.050000   
841                                0.10             0.100000   
842                                0.04             0.050000   
843                                0.03             0.050000   
844                                0.04             0.050000   

     envolvimento_scoretotal  Prev_Cluster  
0                      0.020      0.250000  
1                      0.020      0.250000  
2                      0.025      0.250000  
3                      0.025      0.250000  
4                      0.020      0.125000  
..                       ...           ...  
840                    0.025      0.166667  
841                    0.025      0.500000  
842                    0.020      0.208333  
843                    0.020      0.208333  
844                    0.025      0.416667  

[845 rows x 6 columns]

In [146]:
# Calculate the weighted sum for each entry
weighted_sum = weighted_data.sum(axis=1)

weighted_sum

0      0.470000
1      0.520000
2      0.500000
3      0.526667
4      0.335000
         ...   
840    0.451667
841    0.875000
842    0.408333
843    0.398333
844    0.681667
Length: 845, dtype: float64

In [147]:
# Rank the entries based on the weighted sum
ranked_data = dataset.copy()
ranked_data['Weighted Sum'] = weighted_sum
ranked_data = ranked_data.sort_values('Weighted Sum', ascending=False)
ranked_data['Rank'] = range(1, len(dataset) + 1)


In [149]:
# Display the ranked data
for i, idx in enumerate(ranked_data.index):
    print(f"Rank {i+1}: Alternative {idx+1}")



Rank 1: Alternative 259
Rank 2: Alternative 721
Rank 3: Alternative 542
Rank 4: Alternative 496
Rank 5: Alternative 281
Rank 6: Alternative 446
Rank 7: Alternative 292
Rank 8: Alternative 248
Rank 9: Alternative 113
Rank 10: Alternative 492
Rank 11: Alternative 800
Rank 12: Alternative 418
Rank 13: Alternative 703
Rank 14: Alternative 540
Rank 15: Alternative 497
Rank 16: Alternative 112
Rank 17: Alternative 842
Rank 18: Alternative 436
Rank 19: Alternative 437
Rank 20: Alternative 762
Rank 21: Alternative 752
Rank 22: Alternative 348
Rank 23: Alternative 399
Rank 24: Alternative 361
Rank 25: Alternative 493
Rank 26: Alternative 170
Rank 27: Alternative 500
Rank 28: Alternative 250
Rank 29: Alternative 766
Rank 30: Alternative 144
Rank 31: Alternative 163
Rank 32: Alternative 814
Rank 33: Alternative 384
Rank 34: Alternative 668
Rank 35: Alternative 336
Rank 36: Alternative 544
Rank 37: Alternative 114
Rank 38: Alternative 605
Rank 39: Alternative 453
Rank 40: Alternative 488
Rank 41: 

In [150]:
print("[Nota Pt., Nota Mat., Autoaval., Notas, Envol.Score]")
print(dataset.iloc[258,:].values)
print(dataset.iloc[720,:].values)
print(dataset.iloc[541,:].values)
print(dataset.iloc[495,:].values)
print(dataset.iloc[280,:].values)


print("\nUltimas ranks - Alunos Baixo Risco")
print(dataset.iloc[198,:].values)
print(dataset.iloc[650,:].values)
print(dataset.iloc[60,:].values)
print(dataset.iloc[63,:].values)


[Nota Pt., Nota Mat., Autoaval., Notas, Envol.Score]
[ 2.  2.  1.  1. 18.  0.]
[4. 2. 1. 1. 8. 0.]
[ 2.  3.  1.  1. 19.  0.]
[ 2.  2.  2.  1. 12.  0.]
[ 2.  2.  1.  2. 20.  0.]

Ultimas ranks - Alunos Baixo Risco
[ 5.  5.  5.  5. 25.  3.]
[ 5.  5.  5.  5. 25.  3.]
[ 5.  5.  5.  5. 25.  3.]
[ 5.  5.  5.  5. 25.  3.]
