In [2]:
import numpy as np
import pandas as pd
import joblib
from sklearn.model_selection import cross_val_score
import numpy as np


In [3]:
import pickle
with open('variaveis.pkl', 'rb') as f:
  X_train, Y_train, X_test, Y_teste = pickle.load(f)

In [4]:
import pickle
with open('dataset.pkl', 'rb') as f:
  df,target = pickle.load(f)

In [5]:
print(df)

     Q20__nota_português_2.ºperiodo  Q26__nota_mat_2.ºperiodo  \
0                               4.0                       4.0   
1                               3.0                       3.0   
2                               3.0                       4.0   
3                               3.0                       4.0   
4                               4.0                       4.0   
..                              ...                       ...   
840                             4.0                       2.0   
841                             3.0                       3.0   
842                             5.0                       5.0   
843                             5.0                       5.0   
844                             3.0                       3.0   

     Q16_satisfação_com_notas_escolares  Q15_as_minhas_notas  \
0                                   4.0                  4.0   
1                                   3.0                  3.0   
2                          

In [6]:
print(target)

0      1
1      1
2      1
3      0
4      3
      ..
840    1
841    0
842    3
843    3
844    1
Name: aux, Length: 845, dtype: int64


In [7]:
loaded_model = joblib.load('XGBoost.joblib')
result = loaded_model.score(df, target)
predictions = loaded_model.predict(df)
#print(result)
val_score= cross_val_score(loaded_model, df, target, cv = 10).mean()
print(predictions)

c:\Users\Asus\anaconda3\envs\Tese\lib\site-packages\xgboost\sklearn.py:1395: UserWarning: `use_label_encoder` is deprecated in 1.7.0.
  warnings.warn("`use_label_encoder` is deprecated in 1.7.0.")
c:\Users\Asus\anaconda3\envs\Tese\lib\site-packages\xgboost\sklearn.py:1395: UserWarning: `use_label_encoder` is deprecated in 1.7.0.
  warnings.warn("`use_label_encoder` is deprecated in 1.7.0.")
c:\Users\Asus\anaconda3\envs\Tese\lib\site-packages\xgboost\sklearn.py:1395: UserWarning: `use_label_encoder` is deprecated in 1.7.0.
  warnings.warn("`use_label_encoder` is deprecated in 1.7.0.")
c:\Users\Asus\anaconda3\envs\Tese\lib\site-packages\xgboost\sklearn.py:1395: UserWarning: `use_label_encoder` is deprecated in 1.7.0.
  warnings.warn("`use_label_encoder` is deprecated in 1.7.0.")
c:\Users\Asus\anaconda3\envs\Tese\lib\site-packages\xgboost\sklearn.py:1395: UserWarning: `use_label_encoder` is deprecated in 1.7.0.
  warnings.warn("`use_label_encoder` is deprecated in 1.7.0.")
c:\Users\Asus\a

[1 1 1 1 3 2 1 2 1 3 3 0 1 2 2 1 0 0 2 2 1 3 0 2 0 2 1 2 0 0 2 1 0 2 0 2 0
 2 2 2 3 1 2 0 2 2 2 2 1 2 3 0 3 2 2 2 3 1 3 1 3 3 2 3 0 1 3 0 2 3 3 1 2 2
 1 3 2 0 3 3 1 1 1 3 1 1 2 1 3 2 3 3 1 3 3 2 0 1 3 2 2 2 1 2 0 2 2 0 0 1 0
 0 0 0 1 1 2 0 0 2 3 2 2 0 3 2 1 0 1 1 1 3 3 3 2 2 3 1 0 1 1 1 0 0 0 3 3 1
 3 0 2 2 2 1 2 3 2 1 1 2 1 1 0 1 1 2 0 2 3 0 0 3 1 3 1 2 2 2 1 2 0 1 1 3 1
 1 2 0 1 3 1 0 2 1 2 1 2 2 3 1 3 3 1 1 3 2 0 2 1 1 1 3 1 3 1 1 3 1 2 0 3 2
 3 0 3 1 1 1 1 2 0 0 1 1 0 3 3 3 1 1 1 0 1 0 3 1 1 0 0 0 3 1 2 1 1 1 1 0 0
 3 1 1 1 1 0 1 1 1 3 0 2 0 3 3 1 3 1 0 1 0 0 3 1 2 3 3 2 3 1 3 1 0 0 3 3 2
 3 0 3 3 1 1 2 3 3 2 2 3 1 2 1 1 1 1 2 2 1 1 1 3 0 3 0 3 1 2 2 2 3 1 3 0 2
 0 1 0 1 0 3 0 2 0 0 0 0 1 1 0 1 0 2 3 0 1 2 0 0 0 0 1 0 2 0 2 0 1 0 1 1 0
 2 3 1 1 0 1 0 1 0 3 0 0 0 0 0 3 0 1 0 0 1 1 0 0 0 2 2 2 0 3 1 0 1 1 0 1 3
 2 2 0 3 0 3 3 2 3 2 0 1 2 1 2 2 0 3 2 3 1 3 1 3 2 2 3 1 0 0 3 0 3 2 1 1 0
 1 0 2 2 0 2 2 0 0 0 3 0 2 2 2 2 2 3 2 0 0 3 0 0 1 0 1 3 0 1 0 2 3 0 2 3 3
 1 2 3 2 3 3 0 0 3 3 0 0 

c:\Users\Asus\anaconda3\envs\Tese\lib\site-packages\xgboost\sklearn.py:1395: UserWarning: `use_label_encoder` is deprecated in 1.7.0.
  warnings.warn("`use_label_encoder` is deprecated in 1.7.0.")
c:\Users\Asus\anaconda3\envs\Tese\lib\site-packages\xgboost\sklearn.py:1395: UserWarning: `use_label_encoder` is deprecated in 1.7.0.
  warnings.warn("`use_label_encoder` is deprecated in 1.7.0.")


In [8]:
print(result)

0.9834319526627219


In [9]:
print(val_score)

0.9657002801120449


In [10]:
dataset_final= df 
dataset_final['Prev_Cluster']=predictions

#import pickle

#with open('datasetFinal.pkl', 'wb') as f:
#    pickle.dump(dataset_final,f)

#print(dataset_final.info())

In [11]:
dataset_final.to_pickle('dataset_final.pkl')

In [12]:
dataset_final

Q20__nota_português_2.ºperiodo  Q26__nota_mat_2.ºperiodo  \
0                               4.0                       4.0   
1                               3.0                       3.0   
2                               3.0                       4.0   
3                               3.0                       4.0   
4                               4.0                       4.0   
..                              ...                       ...   
840                             4.0                       2.0   
841                             3.0                       3.0   
842                             5.0                       5.0   
843                             5.0                       5.0   
844                             3.0                       3.0   

     Q16_satisfação_com_notas_escolares  Q15_as_minhas_notas  \
0                                   4.0                  4.0   
1                                   3.0                  3.0   
2                                   4.0                  3.0   
3                                   3.0                  2.0   
4                                   5.0                  4.0   
..                                  ...                  ...   
840                                 3.0                  3.0   
841                                 1.0                  1.0   
842                                 4.0                  3.0   
843                                 5.0                  3.0   
844                                 4.0                  3.0   

     envolvimento_scoretotal  Prev_Cluster  
0                       21.0             1  
1                       23.0             1  
2                       19.0             1  
3                       20.0             1  
4                       22.0             3  
..                       ...           ...  
840                     20.0             2  
841                     19.0             0  
842                     24.0             3  
843                     23.0             3  
844                     18.0             1  

[845 rows x 6 columns]

In [13]:
import pandas as pd
import numpy as np

# Step 1: Load the dataset
# dataset_final

# Step 2: Separate the features and the decision matrix
features = dataset_final.values #features = dataset_final.iloc[:, 1:-1].values  # Assuming the features are in columns 1 to second-last
#decision_matrix = dataset_final.iloc[:, -1].values  # Assuming the decision matrix is in the last column


In [14]:
print(features)
#print(decision_matrix)


[[ 4.  4.  4.  4. 21.  1.]
 [ 3.  3.  3.  3. 23.  1.]
 [ 3.  4.  4.  3. 19.  1.]
 ...
 [ 5.  5.  4.  3. 24.  3.]
 [ 5.  5.  5.  3. 23.  3.]
 [ 3.  3.  4.  3. 18.  1.]]


In [16]:
# Step 3: Normalize the decision matrix
normalized_matrix = features / np.sqrt(np.sum(features ** 2, axis=0))


print(normalized_matrix)

[[0.03672044 0.03603165 0.03519349 0.0458259  0.03646108 0.0182696 ]
 [0.02754033 0.02702374 0.02639512 0.03436943 0.03993356 0.0182696 ]
 [0.02754033 0.03603165 0.03519349 0.03436943 0.0329886  0.0182696 ]
 ...
 [0.04590054 0.04503956 0.03519349 0.03436943 0.04166981 0.05480881]
 [0.04590054 0.04503956 0.04399186 0.03436943 0.03993356 0.05480881]
 [0.02754033 0.02702374 0.03519349 0.03436943 0.03125236 0.0182696 ]]


In [17]:
# Step 4: Define the weight vector (w) and impact vector (I)
weights = [0.1, 0.1, 0.1, 0.1, 0.1, 0.5]  # Adjust the weights based on the importance of each feature
impacts = ['-', '-', '-', '-', '-','-',]  # Adjust the impacts ('+' for maximization, '-' for minimization)

In [18]:
# Step 5: Calculate the weighted normalized decision matrix
weighted_normalized_matrix = normalized_matrix * weights

print(weighted_normalized_matrix)

[[0.00367204 0.00360316 0.00351935 0.00458259 0.00364611 0.0091348 ]
 [0.00275403 0.00270237 0.00263951 0.00343694 0.00399336 0.0091348 ]
 [0.00275403 0.00360316 0.00351935 0.00343694 0.00329886 0.0091348 ]
 ...
 [0.00459005 0.00450396 0.00351935 0.00343694 0.00416698 0.0274044 ]
 [0.00459005 0.00450396 0.00439919 0.00343694 0.00399336 0.0274044 ]
 [0.00275403 0.00270237 0.00351935 0.00343694 0.00312524 0.0091348 ]]


In [19]:
# Step 6: Determine the ideal and negative-ideal solutions
ideal_solution = np.empty(normalized_matrix.shape[1])
negative_ideal_solution = np.empty(normalized_matrix.shape[1])

for i in range(normalized_matrix.shape[1]):
    if impacts[i] == '+':
        ideal_solution[i] = np.max(weighted_normalized_matrix[:, i])
        negative_ideal_solution[i] = np.min(weighted_normalized_matrix[:, i])
    else:
        ideal_solution[i] = np.min(weighted_normalized_matrix[:, i])
        negative_ideal_solution[i] = np.max(weighted_normalized_matrix[:, i])


print(ideal_solution)
print(negative_ideal_solution)

[0.00183602 0.00180158 0.00087984 0.00114565 0.00086812 0.        ]
[0.00459005 0.00450396 0.00439919 0.00572824 0.0043406  0.0274044 ]


In [20]:
# Step 7: Calculate the Euclidean distances from the ideal and negative-ideal solutions
distance_to_ideal = np.sqrt(np.sum((weighted_normalized_matrix - ideal_solution) ** 2, axis=1))
distance_to_negative_ideal = np.sqrt(np.sum((weighted_normalized_matrix - negative_ideal_solution) ** 2, axis=1))

print(distance_to_ideal)
print(distance_to_negative_ideal)

[0.01079621 0.01015935 0.01027904 0.00993603 0.02811634 0.01895771
 0.01071211 0.01909634 0.01029698 0.02816544 0.02797225 0.00400194
 0.01112608 0.01868542 0.01891313 0.01053933 0.00287511 0.00369435
 0.01891313 0.01915053 0.01013224 0.02803254 0.00428055 0.01860154
 0.00388526 0.01870708 0.01046857 0.01893256 0.00417142 0.00398022
 0.01891313 0.00998295 0.00395387 0.01884018 0.00387663 0.01915366
 0.00372723 0.01902132 0.01915053 0.01896263 0.02805402 0.01024856
 0.01872381 0.00410923 0.01898234 0.01900853 0.01864039 0.01870333
 0.010227   0.01903626 0.02810986 0.00378703 0.02801823 0.01893256
 0.01883038 0.01895771 0.0282817  0.0104232  0.02836141 0.01055683
 0.02848391 0.02816701 0.0188934  0.02848391 0.00352885 0.01041451
 0.02807175 0.0041165  0.0188934  0.0281414  0.02824543 0.01063905
 0.01903626 0.01891811 0.01004859 0.02816701 0.01900853 0.00388526
 0.02824768 0.02820608 0.01015994 0.0102575  0.01023937 0.02846326
 0.01084619 0.01068519 0.01893464 0.01029698 0.02818839 0.0189

In [21]:

# Step 8: Calculate the relative closeness to the ideal solution
closeness = distance_to_negative_ideal / (distance_to_ideal + distance_to_negative_ideal)

print(closeness)

[0.63002646 0.64769991 0.64377056 0.65428961 0.06015021 0.33581777
 0.63205457 0.3332789  0.6439077  0.07602488 0.09158697 0.87397292
 0.62342504 0.35079065 0.33721903 0.63775592 0.90664145 0.88239973
 0.33721903 0.33203564 0.64771904 0.08340426 0.8674065  0.35507209
 0.8770021  0.34642709 0.64107565 0.34312704 0.86929025 0.87464779
 0.33721903 0.65313638 0.87610689 0.34718063 0.87753803 0.33885749
 0.88188544 0.34159828 0.33203564 0.33758124 0.0837474  0.64505736
 0.35044823 0.87077001 0.33519864 0.33463473 0.35353783 0.35550159
 0.64543286 0.33412656 0.08030336 0.87976894 0.08642148 0.34312704
 0.34545659 0.33581777 0.04060941 0.64112252 0.04109202 0.63791491
 0.         0.05169773 0.33950191 0.         0.88760769 0.64049027
 0.08245655 0.87100215 0.33950191 0.05984784 0.04528334 0.6343631
 0.33412656 0.33888603 0.64984532 0.05169773 0.33463473 0.8770021
 0.04940401 0.0751309  0.64724166 0.6461192  0.64478679 0.00606296
 0.62975958 0.63411043 0.33649149 0.6439077  0.05236788 0.337219

In [22]:

# Step 9: Rank the alternatives based on the relative closeness
ranked_indices = np.argsort(closeness)[::-1]  # Sort in descending order

# Step 10: Print the ranked alternatives
for i, idx in enumerate(ranked_indices):
    print(f"Rank {i+1}: Alternative {idx+1}")


Rank 1: Alternative 496
Rank 2: Alternative 703
Rank 3: Alternative 436
Rank 4: Alternative 721
Rank 5: Alternative 336
Rank 6: Alternative 248
Rank 7: Alternative 418
Rank 8: Alternative 762
Rank 9: Alternative 259
Rank 10: Alternative 113
Rank 11: Alternative 497
Rank 12: Alternative 453
Rank 13: Alternative 446
Rank 14: Alternative 361
Rank 15: Alternative 492
Rank 16: Alternative 800
Rank 17: Alternative 170
Rank 18: Alternative 250
Rank 19: Alternative 188
Rank 20: Alternative 542
Rank 21: Alternative 437
Rank 22: Alternative 412
Rank 23: Alternative 402
Rank 24: Alternative 814
Rank 25: Alternative 752
Rank 26: Alternative 270
Rank 27: Alternative 356
Rank 28: Alternative 838
Rank 29: Alternative 112
Rank 30: Alternative 163
Rank 31: Alternative 389
Rank 32: Alternative 806
Rank 33: Alternative 773
Rank 34: Alternative 292
Rank 35: Alternative 842
Rank 36: Alternative 128
Rank 37: Alternative 539
Rank 38: Alternative 144
Rank 39: Alternative 338
Rank 40: Alternative 493
Rank 41: 

In [23]:
print("[Nota Pt., Nota Mat., Autoaval., Notas, Envol.Score]")
print(dataset_final.iloc[495,:].values)
print(dataset_final.iloc[702,:].values)
print(dataset_final.iloc[435,:].values)
print(dataset_final.iloc[720,:].values)
print(dataset_final.iloc[335,:].values)
print(dataset_final.iloc[247,:].values)
print(dataset_final.iloc[417,:].values)

print("\nUltimas ranks - Alunos Baixo Risco")
print(dataset_final.iloc[63,:].values)
print(dataset_final.iloc[198,:].values)
print(dataset_final.iloc[742,:].values)
print(dataset_final.iloc[60,:].values)

[Nota Pt., Nota Mat., Autoaval., Notas, Envol.Score]
[ 2.  2.  2.  1. 12.  0.]
[ 3.  3.  1.  1. 12.  0.]
[ 3.  2.  2.  1. 13.  0.]
[4. 2. 1. 1. 8. 0.]
[ 2.  3.  2.  2. 11.  0.]
[ 2.  2.  2.  1. 16.  0.]
[4. 3. 1. 1. 8. 0.]

Ultimas ranks - Alunos Baixo Risco
[ 5.  5.  5.  5. 25.  3.]
[ 5.  5.  5.  5. 25.  3.]
[ 5.  5.  5.  5. 25.  3.]
[ 5.  5.  5.  5. 25.  3.]
