In [385]:
import numpy as np
import pandas as pd


In [386]:
# Step 1: Load the dataset
import pickle
dataset = pd.read_pickle('dataset_final.pkl')

In [387]:

# Step 2: Determine the pairwise comparison matrix and criteria weights

#[Portuguese, math , satifaction, Grades, Envolvement, Risk]

pairwise_matrix = [
    [1, 1, 7, 5, 7, 3],
    [1, 1, 7, 5, 7, 3],
    [1/7, 1/7, 1, 1/4, 1, 1/6],
    [1/5, 1/5, 4, 1, 4, 1/3],
    [1/7, 1/7, 1, 1/4, 1, 1/6],
    [1/3, 1/3, 6, 3, 6, 1]
]

pairwise_matrix



[[1, 1, 7, 5, 7, 3],
 [1, 1, 7, 5, 7, 3],
 [0.14285714285714285, 0.14285714285714285, 1, 0.25, 1, 0.16666666666666666],
 [0.2, 0.2, 4, 1, 4, 0.3333333333333333],
 [0.14285714285714285, 0.14285714285714285, 1, 0.25, 1, 0.16666666666666666],
 [0.3333333333333333, 0.3333333333333333, 6, 3, 6, 1]]

In [388]:
column_sums = np.sum(pairwise_matrix, axis=0)

column_sums

array([ 2.81904762,  2.81904762, 26.        , 14.5       , 26.        ,
        7.66666667])

In [389]:
pairwise_matrix

[[1, 1, 7, 5, 7, 3],
 [1, 1, 7, 5, 7, 3],
 [0.14285714285714285, 0.14285714285714285, 1, 0.25, 1, 0.16666666666666666],
 [0.2, 0.2, 4, 1, 4, 0.3333333333333333],
 [0.14285714285714285, 0.14285714285714285, 1, 0.25, 1, 0.16666666666666666],
 [0.3333333333333333, 0.3333333333333333, 6, 3, 6, 1]]

In [390]:
# Step 3: Calculate the normalized matrix 
#normalized_matrix = [np.divide(x,y) for x,y in zip(pairwise_matrix,column_sums)]

In [391]:
j=0

normalized_matrix = [ [1, 1, 7, 5, 7, 3],
    [1, 1, 7, 5, 7, 3],
    [1/7, 1/7, 1, 1/4, 1, 1/6],
    [1/5, 1/5, 4, 1, 4, 1/3],
    [1/7, 1/7, 1, 1/4, 1, 1/6],
    [1/3, 1/3, 6, 3, 6, 1]
]


for i in range(0,len(normalized_matrix)):
    j = 0
    for k in column_sums:
        normalized_matrix[i][j]= np.divide(pairwise_matrix[i][j],k)    
        j=j+1
    i=i+1 


In [392]:
pairwise_matrix

[[1, 1, 7, 5, 7, 3],
 [1, 1, 7, 5, 7, 3],
 [0.14285714285714285, 0.14285714285714285, 1, 0.25, 1, 0.16666666666666666],
 [0.2, 0.2, 4, 1, 4, 0.3333333333333333],
 [0.14285714285714285, 0.14285714285714285, 1, 0.25, 1, 0.16666666666666666],
 [0.3333333333333333, 0.3333333333333333, 6, 3, 6, 1]]

In [393]:
print(normalized_matrix)


[[0.3547297297297297, 0.3547297297297297, 0.2692307692307692, 0.3448275862068966, 0.2692307692307692, 0.3913043478260869], [0.3547297297297297, 0.3547297297297297, 0.2692307692307692, 0.3448275862068966, 0.2692307692307692, 0.3913043478260869], [0.05067567567567567, 0.05067567567567567, 0.038461538461538464, 0.017241379310344827, 0.038461538461538464, 0.021739130434782608], [0.07094594594594594, 0.07094594594594594, 0.15384615384615385, 0.06896551724137931, 0.15384615384615385, 0.043478260869565216], [0.05067567567567567, 0.05067567567567567, 0.038461538461538464, 0.017241379310344827, 0.038461538461538464, 0.021739130434782608], [0.11824324324324323, 0.11824324324324323, 0.23076923076923078, 0.20689655172413793, 0.23076923076923078, 0.13043478260869565]]


In [394]:
column_sumsTot = np.sum(normalized_matrix, axis=0)

column_sumsTot

array([1., 1., 1., 1., 1., 1.])

In [395]:
weight_vector  = np.mean(normalized_matrix, axis=1)

weight_vector 

array([0.33067549, 0.33067549, 0.03620916, 0.09367133, 0.03620916,
       0.17255938])

In [396]:
row_mean_sum = np.sum(weight_vector)

row_mean_sum

0.9999999999999999

In [397]:
######### ANALISAR CONSISTENCIA

In [398]:
pairwise_matrix

[[1, 1, 7, 5, 7, 3],
 [1, 1, 7, 5, 7, 3],
 [0.14285714285714285, 0.14285714285714285, 1, 0.25, 1, 0.16666666666666666],
 [0.2, 0.2, 4, 1, 4, 0.3333333333333333],
 [0.14285714285714285, 0.14285714285714285, 1, 0.25, 1, 0.16666666666666666],
 [0.3333333333333333, 0.3333333333333333, 6, 3, 6, 1]]

In [399]:
criteria = np.multiply(weight_vector,pairwise_matrix )
criteria

array([[0.33067549, 0.33067549, 0.25346409, 0.46835665, 0.25346409,
        0.51767814],
       [0.33067549, 0.33067549, 0.25346409, 0.46835665, 0.25346409,
        0.51767814],
       [0.04723936, 0.04723936, 0.03620916, 0.02341783, 0.03620916,
        0.0287599 ],
       [0.0661351 , 0.0661351 , 0.14483663, 0.09367133, 0.14483663,
        0.05751979],
       [0.04723936, 0.04723936, 0.03620916, 0.02341783, 0.03620916,
        0.0287599 ],
       [0.11022516, 0.11022516, 0.21725494, 0.28101399, 0.21725494,
        0.17255938]])

In [400]:
weight_sum_value = np.sum(criteria, axis=1)

weight_sum_value

array([2.15431396, 2.15431396, 0.21907475, 0.57313457, 0.21907475,
       1.10853357])

In [401]:
consistencia_col = np.divide(weight_sum_value,weight_vector )

consistencia_col

array([6.51488855, 6.51488855, 6.05025842, 6.11856981, 6.05025842,
       6.42407019])

In [402]:
lambdamax = np.mean(consistencia_col)

lambdamax

6.2788223215008125

In [403]:
consistencia = (lambdamax - 6) / 5

consistencia

0.055764464300162506

In [404]:
consistencia_ratio = consistencia / 1.24

consistencia_ratio

0.04497134217755041

In [405]:
dataset_pesos = np.multiply(dataset,weight_vector )
dataset_pesos

Q20__nota_português_2.ºperiodo  Q26__nota_mat_2.ºperiodo  \
0                          1.322702                  1.322702   
1                          0.992026                  0.992026   
2                          0.992026                  1.322702   
3                          0.992026                  1.322702   
4                          1.322702                  1.322702   
..                              ...                       ...   
840                        1.322702                  0.661351   
841                        0.992026                  0.992026   
842                        1.653377                  1.653377   
843                        1.653377                  1.653377   
844                        0.992026                  0.992026   

     Q16_satisfação_com_notas_escolares  Q15_as_minhas_notas  \
0                              0.144837             0.374685   
1                              0.108627             0.281014   
2                              0.144837             0.281014   
3                              0.108627             0.187343   
4                              0.181046             0.374685   
..                                  ...                  ...   
840                            0.108627             0.281014   
841                            0.036209             0.093671   
842                            0.144837             0.281014   
843                            0.181046             0.281014   
844                            0.144837             0.281014   

     envolvimento_scoretotal  Prev_Cluster  
0                   0.760392      0.172559  
1                   0.832811      0.172559  
2                   0.687974      0.172559  
3                   0.724183      0.172559  
4                   0.796601      0.517678  
..                       ...           ...  
840                 0.724183      0.345119  
841                 0.687974      0.000000  
842                 0.869020      0.517678  
843                 0.832811      0.517678  
844                 0.651765      0.172559  

[845 rows x 6 columns]

In [406]:
coluna_ws = np.sum(dataset_pesos, axis=1)
coluna_ws

0      4.097878
1      3.379064
2      3.601112
3      3.507441
4      4.515415
         ...   
840    3.442996
841    2.801907
842    5.119303
843    5.119303
844    3.234228
Length: 845, dtype: float64

In [407]:
ranked_data = dataset.copy()
ranked_data['Weighted Sum'] = np.sum(dataset_pesos, axis=1)
ranked_data = ranked_data.sort_values('Weighted Sum', ascending=True)
ranked_data['Rank'] = range(1, len(dataset) + 1)

In [408]:
# Display the ranked data
for i, idx in enumerate(ranked_data.index):
    print(f"Rank {i+1}: AlunoId {idx+1}")



Rank 1: AlunoId 496
Rank 2: AlunoId 248
Rank 3: AlunoId 259
Rank 4: AlunoId 113
Rank 5: AlunoId 814
Rank 6: AlunoId 800
Rank 7: AlunoId 112
Rank 8: AlunoId 492
Rank 9: AlunoId 361
Rank 10: AlunoId 446
Rank 11: AlunoId 163
Rank 12: AlunoId 453
Rank 13: AlunoId 250
Rank 14: AlunoId 170
Rank 15: AlunoId 540
Rank 16: AlunoId 292
Rank 17: AlunoId 444
Rank 18: AlunoId 467
Rank 19: AlunoId 114
Rank 20: AlunoId 493
Rank 21: AlunoId 544
Rank 22: AlunoId 281
Rank 23: AlunoId 436
Rank 24: AlunoId 382
Rank 25: AlunoId 468
Rank 26: AlunoId 500
Rank 27: AlunoId 336
Rank 28: AlunoId 249
Rank 29: AlunoId 762
Rank 30: AlunoId 488
Rank 31: AlunoId 721
Rank 32: AlunoId 470
Rank 33: AlunoId 356
Rank 34: AlunoId 497
Rank 35: AlunoId 838
Rank 36: AlunoId 478
Rank 37: AlunoId 542
Rank 38: AlunoId 561
Rank 39: AlunoId 620
Rank 40: AlunoId 17
Rank 41: AlunoId 188
Rank 42: AlunoId 543
Rank 43: AlunoId 829
Rank 44: AlunoId 350
Rank 45: AlunoId 703
Rank 46: AlunoId 822
Rank 47: AlunoId 387
Rank 48: AlunoId 503
Ra

In [409]:
print("[Nota Pt., Nota Mat., Autoaval., Notas, Envol.Score]")
print(dataset.iloc[495,:].values)
print(dataset.iloc[247,:].values)
print(dataset.iloc[258,:].values)
print(dataset.iloc[112,:].values)
print(dataset.iloc[813,:].values)


print("\nUltimas ranks - Alunos Baixo Risco")
print(dataset.iloc[198,:].values)
print(dataset.iloc[60,:].values)
print(dataset.iloc[742,:].values)
print(dataset.iloc[650,:].values)


[Nota Pt., Nota Mat., Autoaval., Notas, Envol.Score]
[ 2.  2.  2.  1. 12.  0.]
[ 2.  2.  2.  1. 16.  0.]
[ 2.  2.  1.  1. 18.  0.]
[ 2.  2.  2.  1. 17.  0.]
[ 2.  2.  3.  2. 14.  0.]

Ultimas ranks - Alunos Baixo Risco
[ 5.  5.  5.  5. 25.  3.]
[ 5.  5.  5.  5. 25.  3.]
[ 5.  5.  5.  5. 25.  3.]
[ 5.  5.  5.  5. 25.  3.]
