In [1]:
import numpy as np
import pandas as pd
import joblib
from sklearn.model_selection import cross_val_score
import numpy as np


In [2]:
import pickle
with open('variaveis.pkl', 'rb') as f:
  X_train, Y_train, X_test, Y_teste = pickle.load(f)

In [3]:
import pickle
with open('dataset.pkl', 'rb') as f:
  df,target = pickle.load(f)

In [4]:
print(df)

     Q20__nota_português_2.ºperiodo  Q26__nota_mat_2.ºperiodo  \
0                               4.0                       4.0   
1                               3.0                       3.0   
2                               3.0                       4.0   
3                               3.0                       4.0   
4                               4.0                       4.0   
..                              ...                       ...   
840                             4.0                       2.0   
841                             3.0                       3.0   
842                             5.0                       5.0   
843                             5.0                       5.0   
844                             3.0                       3.0   

     Q16_satisfação_com_notas_escolares  Q15_as_minhas_notas  \
0                                   4.0                  4.0   
1                                   3.0                  3.0   
2                          

In [5]:
print(target)

0      1
1      1
2      1
3      0
4      3
      ..
840    1
841    0
842    3
843    3
844    1
Name: aux, Length: 845, dtype: int64


In [6]:
loaded_model = joblib.load('XGBoost.joblib')
result = loaded_model.score(df, target)
predictions = loaded_model.predict(df)
#print(result)
val_score= cross_val_score(loaded_model, df, target, cv = 10).mean()
print(predictions)

c:\Users\Asus\anaconda3\envs\Tese\lib\site-packages\xgboost\sklearn.py:1395: UserWarning: `use_label_encoder` is deprecated in 1.7.0.
  warnings.warn("`use_label_encoder` is deprecated in 1.7.0.")
c:\Users\Asus\anaconda3\envs\Tese\lib\site-packages\xgboost\sklearn.py:1395: UserWarning: `use_label_encoder` is deprecated in 1.7.0.
  warnings.warn("`use_label_encoder` is deprecated in 1.7.0.")
c:\Users\Asus\anaconda3\envs\Tese\lib\site-packages\xgboost\sklearn.py:1395: UserWarning: `use_label_encoder` is deprecated in 1.7.0.
  warnings.warn("`use_label_encoder` is deprecated in 1.7.0.")
c:\Users\Asus\anaconda3\envs\Tese\lib\site-packages\xgboost\sklearn.py:1395: UserWarning: `use_label_encoder` is deprecated in 1.7.0.
  warnings.warn("`use_label_encoder` is deprecated in 1.7.0.")
c:\Users\Asus\anaconda3\envs\Tese\lib\site-packages\xgboost\sklearn.py:1395: UserWarning: `use_label_encoder` is deprecated in 1.7.0.
  warnings.warn("`use_label_encoder` is deprecated in 1.7.0.")
c:\Users\Asus\a

[1 1 1 1 3 2 1 2 1 3 3 0 1 2 2 1 0 0 2 2 1 3 0 2 0 2 1 2 0 0 2 1 0 2 0 2 0
 2 2 2 3 1 2 0 2 2 2 2 1 2 3 0 3 2 2 2 3 1 3 1 3 3 2 3 0 1 3 0 2 3 3 1 2 2
 1 3 2 0 3 3 1 1 1 3 1 1 2 1 3 2 3 3 1 3 3 2 0 1 3 2 2 2 1 2 0 2 2 0 0 1 0
 0 0 0 1 1 2 0 0 2 3 2 2 0 3 2 1 0 1 1 1 3 3 3 2 2 3 1 0 1 1 1 0 0 0 3 3 1
 3 0 2 2 2 1 2 3 2 1 1 2 1 1 0 1 1 2 0 2 3 0 0 3 1 3 1 2 2 2 1 2 0 1 1 3 1
 1 2 0 1 3 1 0 2 1 2 1 2 2 3 1 3 3 1 1 3 2 0 2 1 1 1 3 1 3 1 1 3 1 2 0 3 2
 3 0 3 1 1 1 1 2 0 0 1 1 0 3 3 3 1 1 1 0 1 0 3 1 1 0 0 0 3 1 2 1 1 1 1 0 0
 3 1 1 1 1 0 1 1 1 3 0 2 0 3 3 1 3 1 0 1 0 0 3 1 2 3 3 2 3 1 3 1 0 0 3 3 2
 3 0 3 3 1 1 2 3 3 2 2 3 1 2 1 1 1 1 2 2 1 1 1 3 0 3 0 3 1 2 2 2 3 1 3 0 2
 0 1 0 1 0 3 0 2 0 0 0 0 1 1 0 1 0 2 3 0 1 2 0 0 0 0 1 0 2 0 2 0 1 0 1 1 0
 2 3 1 1 0 1 0 1 0 3 0 0 0 0 0 3 0 1 0 0 1 1 0 0 0 2 2 2 0 3 1 0 1 1 0 1 3
 2 2 0 3 0 3 3 2 3 2 0 1 2 1 2 2 0 3 2 3 1 3 1 3 2 2 3 1 0 0 3 0 3 2 1 1 0
 1 0 2 2 0 2 2 0 0 0 3 0 2 2 2 2 2 3 2 0 0 3 0 0 1 0 1 3 0 1 0 2 3 0 2 3 3
 1 2 3 2 3 3 0 0 3 3 0 0 

In [7]:
print(result)

0.9834319526627219


In [8]:
print(val_score)

0.9657002801120449


In [9]:
dataset_final= df 
dataset_final['Prev_Cluster']=predictions

#import pickle

#with open('datasetFinal.pkl', 'wb') as f:
#    pickle.dump(dataset_final,f)

#print(dataset_final.info())

In [10]:
dataset_final.to_pickle('dataset_final.pkl')

In [11]:
dataset_final

Q20__nota_português_2.ºperiodo  Q26__nota_mat_2.ºperiodo  \
0                               4.0                       4.0   
1                               3.0                       3.0   
2                               3.0                       4.0   
3                               3.0                       4.0   
4                               4.0                       4.0   
..                              ...                       ...   
840                             4.0                       2.0   
841                             3.0                       3.0   
842                             5.0                       5.0   
843                             5.0                       5.0   
844                             3.0                       3.0   

     Q16_satisfação_com_notas_escolares  Q15_as_minhas_notas  \
0                                   4.0                  4.0   
1                                   3.0                  3.0   
2                                   4.0                  3.0   
3                                   3.0                  2.0   
4                                   5.0                  4.0   
..                                  ...                  ...   
840                                 3.0                  3.0   
841                                 1.0                  1.0   
842                                 4.0                  3.0   
843                                 5.0                  3.0   
844                                 4.0                  3.0   

     envolvimento_scoretotal  Prev_Cluster  
0                       21.0             1  
1                       23.0             1  
2                       19.0             1  
3                       20.0             1  
4                       22.0             3  
..                       ...           ...  
840                     20.0             2  
841                     19.0             0  
842                     24.0             3  
843                     23.0             3  
844                     18.0             1  

[845 rows x 6 columns]

In [12]:
import pandas as pd
import numpy as np

# Step 1: Load the dataset
# dataset_final

# Step 2: Separate the features and the decision matrix
features = dataset_final.values #features = dataset_final.iloc[:, 1:-1].values  # Assuming the features are in columns 1 to second-last
#decision_matrix = dataset_final.iloc[:, -1].values  # Assuming the decision matrix is in the last column


In [13]:
print(features)
#print(decision_matrix)


[[ 4.  4.  4.  4. 21.  1.]
 [ 3.  3.  3.  3. 23.  1.]
 [ 3.  4.  4.  3. 19.  1.]
 ...
 [ 5.  5.  4.  3. 24.  3.]
 [ 5.  5.  5.  3. 23.  3.]
 [ 3.  3.  4.  3. 18.  1.]]


In [14]:
# Step 3: Normalize the decision matrix
normalized_matrix = features / np.sqrt(np.sum(features ** 2, axis=0))


print(normalized_matrix)

[[0.03672044 0.03603165 0.03519349 0.0458259  0.03646108 0.0182696 ]
 [0.02754033 0.02702374 0.02639512 0.03436943 0.03993356 0.0182696 ]
 [0.02754033 0.03603165 0.03519349 0.03436943 0.0329886  0.0182696 ]
 ...
 [0.04590054 0.04503956 0.03519349 0.03436943 0.04166981 0.05480881]
 [0.04590054 0.04503956 0.04399186 0.03436943 0.03993356 0.05480881]
 [0.02754033 0.02702374 0.03519349 0.03436943 0.03125236 0.0182696 ]]


In [15]:
# Step 4: Define the weight vector (w) and impact vector (I)
weights = [0.25, 0.25, 0.075, 0.15, 0.075, 0.2]   # Adjust the weights based on the importance of each feature
impacts = ['-', '-', '-', '-', '-','-',]  # Adjust the impacts ('+' for maximization, '-' for minimization)

In [16]:
# Step 5: Calculate the weighted normalized decision matrix
weighted_normalized_matrix = normalized_matrix * weights

print(weighted_normalized_matrix)

[[0.00918011 0.00900791 0.00263951 0.00687389 0.00273458 0.00365392]
 [0.00688508 0.00675593 0.00197963 0.00515541 0.00299502 0.00365392]
 [0.00688508 0.00900791 0.00263951 0.00515541 0.00247414 0.00365392]
 ...
 [0.01147514 0.01125989 0.00263951 0.00515541 0.00312524 0.01096176]
 [0.01147514 0.01125989 0.00329939 0.00515541 0.00299502 0.01096176]
 [0.00688508 0.00675593 0.00263951 0.00515541 0.00234393 0.00365392]]


In [17]:
# Step 6: Determine the ideal and negative-ideal solutions
ideal_solution = np.empty(normalized_matrix.shape[1])
negative_ideal_solution = np.empty(normalized_matrix.shape[1])

for i in range(normalized_matrix.shape[1]):
    if impacts[i] == '+':
        ideal_solution[i] = np.max(weighted_normalized_matrix[:, i])
        negative_ideal_solution[i] = np.min(weighted_normalized_matrix[:, i])
    else:
        ideal_solution[i] = np.min(weighted_normalized_matrix[:, i])
        negative_ideal_solution[i] = np.max(weighted_normalized_matrix[:, i])


print(ideal_solution)
print(negative_ideal_solution)

[0.00459005 0.00450396 0.00065988 0.00171847 0.00065109 0.        ]
[0.01147514 0.01125989 0.00329939 0.00859236 0.00325545 0.01096176]


In [18]:
# Step 7: Calculate the Euclidean distances from the ideal and negative-ideal solutions
distance_to_ideal = np.sqrt(np.sum((weighted_normalized_matrix - ideal_solution) ** 2, axis=1))
distance_to_negative_ideal = np.sqrt(np.sum((weighted_normalized_matrix - negative_ideal_solution) ** 2, axis=1))

print(distance_to_ideal)
print(distance_to_negative_ideal)

[0.00946274 0.00653743 0.00761308 0.00688579 0.01414073 0.01069138
 0.00940883 0.01082927 0.00665746 0.01541041 0.0152112  0.00587168
 0.00890123 0.01009433 0.01064688 0.0078107  0.00341434 0.00509359
 0.01064688 0.01088296 0.00750157 0.0152735  0.00388585 0.00928931
 0.00517287 0.00975452 0.00925336 0.01035011 0.00484153 0.00453146
 0.01064688 0.00692385 0.00426635 0.009556   0.00448066 0.01161622
 0.00576908 0.01044126 0.01088296 0.01172542 0.0144911  0.0066153
 0.00942647 0.00526932 0.01071593 0.01074201 0.00933301 0.00940357
 0.00757356 0.0107696  0.01535322 0.00513173 0.01363041 0.01035011
 0.01024472 0.01069138 0.01588227 0.00676704 0.01644051 0.00688257
 0.0165592  0.01576721 0.00995446 0.0165592  0.00431598 0.00771595
 0.0145104  0.00459944 0.00995446 0.01499063 0.01584593 0.00859091
 0.0107696  0.00998083 0.00743801 0.01576721 0.01074201 0.00517287
 0.01507314 0.01545217 0.00653795 0.00626501 0.00758295 0.01653922
 0.00870475 0.00859201 0.01066836 0.00665746 0.01501057 0.01064

In [19]:

# Step 8: Calculate the relative closeness to the ideal solution
closeness = distance_to_negative_ideal / (distance_to_ideal + distance_to_negative_ideal)

print(closeness)

[0.46455511 0.61426638 0.55804022 0.60179261 0.20590612 0.36061851
 0.46660112 0.35632315 0.60859763 0.18278399 0.19358193 0.69239887
 0.5050487  0.41923064 0.3628664  0.55112654 0.81179318 0.7228242
 0.3628664  0.35428524 0.56315849 0.18808794 0.79775941 0.47134738
 0.71940846 0.42927761 0.48165925 0.40773605 0.7450604  0.75216542
 0.3628664  0.60030162 0.77277389 0.45963553 0.75436903 0.3669774
 0.69757072 0.40506864 0.35428524 0.32746877 0.2232704  0.61024153
 0.46476988 0.71540842 0.3596053  0.35866802 0.46918883 0.46987423
 0.56044971 0.35780794 0.18563239 0.72116271 0.25695984 0.40773605
 0.41149649 0.36061851 0.0986412  0.60472678 0.05253143 0.60015966
 0.         0.10662383 0.41909384 0.         0.76257553 0.55411376
 0.22244552 0.74973255 0.41909384 0.16389695 0.10178642 0.51432797
 0.35780794 0.41808943 0.56578414 0.10662383 0.35866802 0.71940846
 0.15981419 0.18195364 0.61340962 0.64756969 0.55931164 0.00781179
 0.51154843 0.51695227 0.36170613 0.60859763 0.16161582 0.362866

In [20]:

# Step 9: Rank the alternatives based on the relative closeness
ranked_indices = np.argsort(closeness)[::-1]  # Sort in descending order

# Step 10: Print the ranked alternatives
for i, idx in enumerate(ranked_indices):
    print(f"Rank {i+1}: AlunoId {idx+1}")


Rank 1: AlunoId 496
Rank 2: AlunoId 248
Rank 3: AlunoId 259
Rank 4: AlunoId 113
Rank 5: AlunoId 492
Rank 6: AlunoId 800
Rank 7: AlunoId 112
Rank 8: AlunoId 292
Rank 9: AlunoId 540
Rank 10: AlunoId 446
Rank 11: AlunoId 361
Rank 12: AlunoId 250
Rank 13: AlunoId 170
Rank 14: AlunoId 814
Rank 15: AlunoId 163
Rank 16: AlunoId 281
Rank 17: AlunoId 493
Rank 18: AlunoId 436
Rank 19: AlunoId 114
Rank 20: AlunoId 500
Rank 21: AlunoId 762
Rank 22: AlunoId 544
Rank 23: AlunoId 542
Rank 24: AlunoId 467
Rank 25: AlunoId 488
Rank 26: AlunoId 336
Rank 27: AlunoId 497
Rank 28: AlunoId 453
Rank 29: AlunoId 188
Rank 30: AlunoId 838
Rank 31: AlunoId 356
Rank 32: AlunoId 703
Rank 33: AlunoId 365
Rank 34: AlunoId 353
Rank 35: AlunoId 699
Rank 36: AlunoId 17
Rank 37: AlunoId 620
Rank 38: AlunoId 167
Rank 39: AlunoId 358
Rank 40: AlunoId 808
Rank 41: AlunoId 363
Rank 42: AlunoId 829
Rank 43: AlunoId 494
Rank 44: AlunoId 348
Rank 45: AlunoId 454
Rank 46: AlunoId 503
Rank 47: AlunoId 513
Rank 48: AlunoId 473
Ra

In [22]:
print("[Nota Pt., Nota Mat., Autoaval., Notas, Envol.Score]")
print(dataset_final.iloc[495,:].values)
print(dataset_final.iloc[247,:].values)
print(dataset_final.iloc[258,:].values)
print(dataset_final.iloc[112,:].values)
print(dataset_final.iloc[491,:].values)
print(dataset_final.iloc[799,:].values)
print(dataset_final.iloc[111,:].values)

print("\nUltimas ranks - Alunos Baixo Risco")
print(dataset_final.iloc[63,:].values)
print(dataset_final.iloc[650,:].values)
print(dataset_final.iloc[60,:].values)
print(dataset_final.iloc[742,:].values)

[Nota Pt., Nota Mat., Autoaval., Notas, Envol.Score]
[ 2.  2.  2.  1. 12.  0.]
[ 2.  2.  2.  1. 16.  0.]
[ 2.  2.  1.  1. 18.  0.]
[ 2.  2.  2.  1. 17.  0.]
[ 2.  2.  2.  1. 18.  0.]
[ 2.  2.  2.  1. 18.  0.]
[ 2.  2.  3.  1. 17.  0.]

Ultimas ranks - Alunos Baixo Risco
[ 5.  5.  5.  5. 25.  3.]
[ 5.  5.  5.  5. 25.  3.]
[ 5.  5.  5.  5. 25.  3.]
[ 5.  5.  5.  5. 25.  3.]
