In [1]:
import numpy as np
import pandas as pd
import math

In [2]:
# Step 1: Load the dataset
import pickle
dataset = pd.read_pickle('dataset_final.pkl')

In [3]:
dataset

Q20__nota_português_2.ºperiodo  Q26__nota_mat_2.ºperiodo  \
0                               4.0                       4.0   
1                               3.0                       3.0   
2                               3.0                       4.0   
3                               3.0                       4.0   
4                               4.0                       4.0   
..                              ...                       ...   
840                             4.0                       2.0   
841                             3.0                       3.0   
842                             5.0                       5.0   
843                             5.0                       5.0   
844                             3.0                       3.0   

     Q16_satisfação_com_notas_escolares  Q15_as_minhas_notas  \
0                                   4.0                  4.0   
1                                   3.0                  3.0   
2                                   4.0                  3.0   
3                                   3.0                  2.0   
4                                   5.0                  4.0   
..                                  ...                  ...   
840                                 3.0                  3.0   
841                                 1.0                  1.0   
842                                 4.0                  3.0   
843                                 5.0                  3.0   
844                                 4.0                  3.0   

     envolvimento_scoretotal  Prev_Cluster  
0                       21.0             1  
1                       23.0             1  
2                       19.0             1  
3                       20.0             1  
4                       22.0             3  
..                       ...           ...  
840                     20.0             2  
841                     19.0             0  
842                     24.0             3  
843                     23.0             3  
844                     18.0             1  

[845 rows x 6 columns]

In [4]:
column_sum = np.sum(dataset,axis=0)

column_sum

Q20__nota_português_2.ºperiodo         3094.0
Q26__nota_mat_2.ºperiodo               3130.0
Q16_satisfação_com_notas_escolares     3190.0
Q15_as_minhas_notas                    2431.0
envolvimento_scoretotal               16510.0
Prev_Cluster                           1282.0
dtype: float64

In [5]:
norm_values = np.divide(dataset,column_sum)

norm_values

Q20__nota_português_2.ºperiodo  Q26__nota_mat_2.ºperiodo  \
0                          0.001293                  0.001278   
1                          0.000970                  0.000958   
2                          0.000970                  0.001278   
3                          0.000970                  0.001278   
4                          0.001293                  0.001278   
..                              ...                       ...   
840                        0.001293                  0.000639   
841                        0.000970                  0.000958   
842                        0.001616                  0.001597   
843                        0.001616                  0.001597   
844                        0.000970                  0.000958   

     Q16_satisfação_com_notas_escolares  Q15_as_minhas_notas  \
0                              0.001254             0.001645   
1                              0.000940             0.001234   
2                              0.001254             0.001234   
3                              0.000940             0.000823   
4                              0.001567             0.001645   
..                                  ...                  ...   
840                            0.000940             0.001234   
841                            0.000313             0.000411   
842                            0.001254             0.001234   
843                            0.001567             0.001234   
844                            0.001254             0.001234   

     envolvimento_scoretotal  Prev_Cluster  
0                   0.001272       0.00078  
1                   0.001393       0.00078  
2                   0.001151       0.00078  
3                   0.001211       0.00078  
4                   0.001333       0.00234  
..                       ...           ...  
840                 0.001211       0.00156  
841                 0.001151       0.00000  
842                 0.001454       0.00234  
843                 0.001393       0.00234  
844                 0.001090       0.00078  

[845 rows x 6 columns]

In [6]:
h = 1 / math.log(len(dataset))

h

0.1483825568143714

In [7]:
entropy = np.sum(norm_values * np.log2(norm_values))

entropy

c:\Users\Asus\anaconda3\envs\Tese\lib\site-packages\pandas\core\internals\blocks.py:402: RuntimeWarning: divide by zero encountered in log2
  result = func(self.values, **kwargs)


Q20__nota_português_2.ºperiodo       -9.687739
Q26__nota_mat_2.ºperiodo             -9.675884
Q16_satisfação_com_notas_escolares   -9.664162
Q15_as_minhas_notas                  -9.657268
envolvimento_scoretotal              -9.701117
Prev_Cluster                         -9.189222
dtype: float64

In [8]:
entropies = -h * entropy

entropies

Q20__nota_português_2.ºperiodo        1.437491
Q26__nota_mat_2.ºperiodo              1.435732
Q16_satisfação_com_notas_escolares    1.433993
Q15_as_minhas_notas                   1.432970
envolvimento_scoretotal               1.439477
Prev_Cluster                          1.363520
dtype: float64

In [9]:
d = 1-entropies

d

Q20__nota_português_2.ºperiodo       -0.437491
Q26__nota_mat_2.ºperiodo             -0.435732
Q16_satisfação_com_notas_escolares   -0.433993
Q15_as_minhas_notas                  -0.432970
envolvimento_scoretotal              -0.439477
Prev_Cluster                         -0.363520
dtype: float64

In [10]:
sum_d = np.sum(d)

sum_d

-2.543183855910941

In [11]:
weight_vector = np.divide(d,sum_d)

weight_vector

Q20__nota_português_2.ºperiodo        0.172025
Q26__nota_mat_2.ºperiodo              0.171333
Q16_satisfação_com_notas_escolares    0.170649
Q15_as_minhas_notas                   0.170247
envolvimento_scoretotal               0.172806
Prev_Cluster                          0.142939
dtype: float64

In [12]:
weight_vector.tolist()

[0.17202511458634429,
 0.17133341698997043,
 0.17064949815892275,
 0.17024725535006752,
 0.17280566459135063,
 0.1429390503233443]

In [13]:
dataset_pesos = np.multiply(dataset,weight_vector )
dataset_pesos

Q20__nota_português_2.ºperiodo  Q26__nota_mat_2.ºperiodo  \
0                          0.688100                  0.685334   
1                          0.516075                  0.514000   
2                          0.516075                  0.685334   
3                          0.516075                  0.685334   
4                          0.688100                  0.685334   
..                              ...                       ...   
840                        0.688100                  0.342667   
841                        0.516075                  0.514000   
842                        0.860126                  0.856667   
843                        0.860126                  0.856667   
844                        0.516075                  0.514000   

     Q16_satisfação_com_notas_escolares  Q15_as_minhas_notas  \
0                              0.682598             0.680989   
1                              0.511948             0.510742   
2                              0.682598             0.510742   
3                              0.511948             0.340495   
4                              0.853247             0.680989   
..                                  ...                  ...   
840                            0.511948             0.510742   
841                            0.170649             0.170247   
842                            0.682598             0.510742   
843                            0.853247             0.510742   
844                            0.682598             0.510742   

     envolvimento_scoretotal  Prev_Cluster  
0                   3.628919      0.142939  
1                   3.974530      0.142939  
2                   3.283308      0.142939  
3                   3.456113      0.142939  
4                   3.801725      0.428817  
..                       ...           ...  
840                 3.456113      0.285878  
841                 3.283308      0.000000  
842                 4.147336      0.428817  
843                 3.974530      0.428817  
844                 3.110502      0.142939  

[845 rows x 6 columns]

In [14]:
ranked_data = dataset.copy()
ranked_data['Weighted Sum'] = np.sum(dataset_pesos, axis=1)
ranked_data = ranked_data.sort_values('Weighted Sum', ascending=True)
ranked_data['Rank'] = range(1, len(dataset) + 1)

In [15]:
# Display the ranked data
for i, idx in enumerate(ranked_data.index):
    print(f"Rank {i+1}: AlunoId {idx+1}")



Rank 1: AlunoId 453
Rank 2: AlunoId 721
Rank 3: AlunoId 418
Rank 4: AlunoId 496
Rank 5: AlunoId 412
Rank 6: AlunoId 336
Rank 7: AlunoId 703
Rank 8: AlunoId 470
Rank 9: AlunoId 436
Rank 10: AlunoId 458
Rank 11: AlunoId 465
Rank 12: AlunoId 478
Rank 13: AlunoId 270
Rank 14: AlunoId 118
Rank 15: AlunoId 108
Rank 16: AlunoId 452
Rank 17: AlunoId 128
Rank 18: AlunoId 539
Rank 19: AlunoId 838
Rank 20: AlunoId 356
Rank 21: AlunoId 814
Rank 22: AlunoId 497
Rank 23: AlunoId 762
Rank 24: AlunoId 248
Rank 25: AlunoId 97
Rank 26: AlunoId 242
Rank 27: AlunoId 444
Rank 28: AlunoId 543
Rank 29: AlunoId 163
Rank 30: AlunoId 361
Rank 31: AlunoId 752
Rank 32: AlunoId 446
Rank 33: AlunoId 113
Rank 34: AlunoId 259
Rank 35: AlunoId 367
Rank 36: AlunoId 832
Rank 37: AlunoId 340
Rank 38: AlunoId 822
Rank 39: AlunoId 321
Rank 40: AlunoId 387
Rank 41: AlunoId 746
Rank 42: AlunoId 677
Rank 43: AlunoId 657
Rank 44: AlunoId 545
Rank 45: AlunoId 334
Rank 46: AlunoId 17
Rank 47: AlunoId 620
Rank 48: AlunoId 510
Ran

In [16]:
print("[Nota Pt., Nota Mat., Autoaval., Notas, Envol.Score]")
print(dataset.iloc[452,:].values)
print(dataset.iloc[720,:].values)
print(dataset.iloc[417,:].values)
print(dataset.iloc[495,:].values)
print(dataset.iloc[411,:].values)


print("\nUltimas ranks - Alunos Baixo Risco")
print(dataset.iloc[63,:].values)
print(dataset.iloc[650,:].values)
print(dataset.iloc[198,:].values)
print(dataset.iloc[742,:].values)
print(dataset.iloc[60,:].values)

[Nota Pt., Nota Mat., Autoaval., Notas, Envol.Score]
[3. 2. 3. 2. 6. 0.]
[4. 2. 1. 1. 8. 0.]
[4. 3. 1. 1. 8. 0.]
[ 2.  2.  2.  1. 12.  0.]
[3. 4. 2. 2. 9. 0.]

Ultimas ranks - Alunos Baixo Risco
[ 5.  5.  5.  5. 25.  3.]
[ 5.  5.  5.  5. 25.  3.]
[ 5.  5.  5.  5. 25.  3.]
[ 5.  5.  5.  5. 25.  3.]
[ 5.  5.  5.  5. 25.  3.]
