In [1]:
import numpy as np
import pandas as pd

In [2]:
dataset = pd.read_pickle('../pickle/dataset_final.pkl')

In [3]:
weights = [0.17202511458634429, 0.17133341698997043, 0.17064949815892275, 0.17024725535006752, 0.17280566459135063,  0.1429390503233443]

In [4]:
dataset_Moora = pd.read_pickle('../pickle/norm_MOORA.pkl') 

In [5]:
#Calculate the weighted normalized matrix
weighted_matrix = dataset_Moora.iloc[:, :] * weights

weighted_matrix

Q20__nota_português_2.ºperiodo  Q26__nota_mat_2.ºperiodo  \
0                          0.006317                  0.006173   
1                          0.004738                  0.004630   
2                          0.004738                  0.006173   
3                          0.004738                  0.006173   
4                          0.006317                  0.006173   
..                              ...                       ...   
840                        0.006317                  0.003087   
841                        0.004738                  0.004630   
842                        0.007896                  0.007717   
843                        0.007896                  0.007717   
844                        0.004738                  0.004630   

     Q16_satisfação_com_notas_escolares  Q15_as_minhas_notas  \
0                              0.006006             0.007802   
1                              0.004504             0.005851   
2                              0.006006             0.005851   
3                              0.004504             0.003901   
4                              0.007507             0.007802   
..                                  ...                  ...   
840                            0.004504             0.005851   
841                            0.001501             0.001950   
842                            0.006006             0.005851   
843                            0.007507             0.005851   
844                            0.006006             0.005851   

     envolvimento_scoretotal  Prev_Cluster  
0                   0.006301      0.002611  
1                   0.006901      0.002611  
2                   0.005701      0.002611  
3                   0.006001      0.002611  
4                   0.006601      0.007834  
..                       ...           ...  
840                 0.006001      0.005223  
841                 0.005701      0.000000  
842                 0.007201      0.007834  
843                 0.006901      0.007834  
844                 0.005401      0.002611  

[845 rows x 6 columns]

In [6]:
y = np.sum(weighted_matrix,axis=1)

In [7]:
ranked_data = dataset_Moora.copy()
ranked_data['Weighted Sum'] = y
ranked_data = ranked_data.sort_values('Weighted Sum', ascending=True)
ranked_data['Rank'] = range(1, len(dataset_Moora) + 1)

In [8]:
# Display the ranked data
for i, idx in enumerate(ranked_data.index):
    print(f"Rank {i+1}: AlunoId {idx+1}")

Rank 1: AlunoId 496
Rank 2: AlunoId 259
Rank 3: AlunoId 721
Rank 4: AlunoId 248
Rank 5: AlunoId 113
Rank 6: AlunoId 703
Rank 7: AlunoId 800
Rank 8: AlunoId 492
Rank 9: AlunoId 436
Rank 10: AlunoId 446
Rank 11: AlunoId 418
Rank 12: AlunoId 542
Rank 13: AlunoId 292
Rank 14: AlunoId 762
Rank 15: AlunoId 281
Rank 16: AlunoId 497
Rank 17: AlunoId 112
Rank 18: AlunoId 361
Rank 19: AlunoId 336
Rank 20: AlunoId 453
Rank 21: AlunoId 437
Rank 22: AlunoId 170
Rank 23: AlunoId 250
Rank 24: AlunoId 540
Rank 25: AlunoId 842
Rank 26: AlunoId 493
Rank 27: AlunoId 814
Rank 28: AlunoId 752
Rank 29: AlunoId 144
Rank 30: AlunoId 500
Rank 31: AlunoId 163
Rank 32: AlunoId 348
Rank 33: AlunoId 188
Rank 34: AlunoId 114
Rank 35: AlunoId 399
Rank 36: AlunoId 668
Rank 37: AlunoId 544
Rank 38: AlunoId 699
Rank 39: AlunoId 353
Rank 40: AlunoId 365
Rank 41: AlunoId 356
Rank 42: AlunoId 838
Rank 43: AlunoId 766
Rank 44: AlunoId 384
Rank 45: AlunoId 605
Rank 46: AlunoId 338
Rank 47: AlunoId 167
Rank 48: AlunoId 808
R

In [9]:
print("[Nota Pt., Nota Mat., Autoaval., Notas, Envol.Score]")
print(dataset.iloc[495,:].values)
print(dataset.iloc[258,:].values)
print(dataset.iloc[720,:].values)
print(dataset.iloc[247,:].values)
print(dataset.iloc[112,:].values)


print("\nUltimas ranks - Alunos Baixo Risco")
print(dataset.iloc[198,:].values)
print(dataset.iloc[60,:].values)
print(dataset.iloc[742,:].values)
print(dataset.iloc[651,:].values)
print(dataset.iloc[63,:].values)

[Nota Pt., Nota Mat., Autoaval., Notas, Envol.Score]
[ 2.  2.  2.  1. 12.  0.]
[ 2.  2.  1.  1. 18.  0.]
[4. 2. 1. 1. 8. 0.]
[ 2.  2.  2.  1. 16.  0.]
[ 2.  2.  2.  1. 17.  0.]

Ultimas ranks - Alunos Baixo Risco
[ 5.  5.  5.  5. 25.  3.]
[ 5.  5.  5.  5. 25.  3.]
[ 5.  5.  5.  5. 25.  3.]
[ 4.  5.  5.  3. 23.  3.]
[ 5.  5.  5.  5. 25.  3.]
