In [23]:
import numpy as np
import pandas as pd
from uwTOPSIS.uwTOPSIS import *


In [24]:
# Step 1: Load the dataset
import pickle
dataset = pd.read_pickle('dataset_final.pkl')

In [25]:
features = dataset.values
features


array([[ 4.,  4.,  4.,  4., 21.,  1.],
       [ 3.,  3.,  3.,  3., 23.,  1.],
       [ 3.,  4.,  4.,  3., 19.,  1.],
       ...,
       [ 5.,  5.,  4.,  3., 24.,  3.],
       [ 5.,  5.,  5.,  3., 23.,  3.],
       [ 3.,  3.,  4.,  3., 18.,  1.]])

In [26]:
impacts = ["min", "min", "min", "min", "min","min"]

In [27]:
#L: array with the lower bounds of the weigths.

L = np.repeat(0.1, dataset.shape[1])

L

array([0.1, 0.1, 0.1, 0.1, 0.1, 0.1])

In [28]:
#U: array with the upper bounds of the weigths.
U = np.repeat(0.4, dataset.shape[1])

U

array([0.4, 0.4, 0.4, 0.4, 0.4, 0.4])

In [29]:
norm = "euclidean" # "euclidean", "gauss", "minmax"

In [30]:
#integer value for the L-p distance. (By default p=2)

p = 2

In [31]:
x = uwTOPSIS(dataset, impacts, L, U, norm, p)

c:\Users\Asus\Desktop\Tese\uwTOPSIS\uwTOPSIS.py:117: RuntimeWarning: invalid value encountered in double_scalars
  d_Antiideal_partial = w[k]*(Antiideal[k]-data[i][k])**2/d_Antiideal


In [36]:
x.keys()

dict_keys(['Ranking', 'Weights_min', 'Weights_max'])

In [47]:
x['Ranking']['uwTOPSIS']

[0.4388039676092219,
 0.4769593823973719,
 0.48214637835152985,
 0.5105221928735139,
 0.14989145538535278,
 0.3702096744196429,
 0.4524792633845198,
 0.3197904567559389,
 0.4628084623562786,
 0.2466937452738237,
 0.2645794178481214,
 0.6208730541270333,
 0.39895245673180674,
 0.5014494305972186,
 0.3786505400692729,
 0.4344767228353452,
 0.7227112235201892,
 0.6790784068421962,
 0.3786505400692729,
 0.31006280990687624,
 0.4929578723957654,
 0.2563016948533617,
 0.5945681043448039,
 0.5104278041229283,
 0.650146797004223,
 0.4169248278644994,
 0.47015404326474225,
 0.43744205946368603,
 0.6177849656027194,
 0.6197062815281731,
 0.3786505400692729,
 0.4978340172078416,
 0.6112372994080787,
 0.4576749705160762,
 0.6248040062676781,
 0.41225194036759477,
 0.6237119323558589,
 0.42039618294607267,
 0.31006280990687624,
 0.351381640992108,
 0.25588542477299914,
 0.47385103382641236,
 0.48881326860904883,
 0.6218762192548783,
 0.3559984986943395,
 0.343345532591994,
 0.5067406162948064,
 0.4

In [48]:
ranked_data = dataset.copy()
ranked_data['Ranking'] = x['Ranking']['uwTOPSIS']
ranked_data = ranked_data.sort_values('Ranking', ascending=False)
ranked_data['Rank'] = range(1, len(dataset) + 1)



In [49]:
# Display the ranked data
for i, idx in enumerate(ranked_data.index):
    print(f"Rank {i+1}: AlunoId {idx+1}")


Rank 1: AlunoId 496
Rank 2: AlunoId 703
Rank 3: AlunoId 336
Rank 4: AlunoId 436
Rank 5: AlunoId 762
Rank 6: AlunoId 721
Rank 7: AlunoId 248
Rank 8: AlunoId 497
Rank 9: AlunoId 453
Rank 10: AlunoId 361
Rank 11: AlunoId 418
Rank 12: AlunoId 402
Rank 13: AlunoId 113
Rank 14: AlunoId 814
Rank 15: AlunoId 446
Rank 16: AlunoId 270
Rank 17: AlunoId 838
Rank 18: AlunoId 356
Rank 19: AlunoId 539
Rank 20: AlunoId 128
Rank 21: AlunoId 259
Rank 22: AlunoId 163
Rank 23: AlunoId 338
Rank 24: AlunoId 188
Rank 25: AlunoId 250
Rank 26: AlunoId 170
Rank 27: AlunoId 17
Rank 28: AlunoId 620
Rank 29: AlunoId 334
Rank 30: AlunoId 657
Rank 31: AlunoId 545
Rank 32: AlunoId 492
Rank 33: AlunoId 800
Rank 34: AlunoId 389
Rank 35: AlunoId 773
Rank 36: AlunoId 806
Rank 37: AlunoId 412
Rank 38: AlunoId 752
Rank 39: AlunoId 510
Rank 40: AlunoId 470
Rank 41: AlunoId 112
Rank 42: AlunoId 478
Rank 43: AlunoId 437
Rank 44: AlunoId 444
Rank 45: AlunoId 144
Rank 46: AlunoId 829
Rank 47: AlunoId 543
Rank 48: AlunoId 298
Ra

In [50]:
print("[Nota Pt., Nota Mat., Autoaval., Notas, Envol.Score]")
print(dataset.iloc[495,:].values)
print(dataset.iloc[702,:].values)
print(dataset.iloc[335,:].values)
print(dataset.iloc[435,:].values)
print(dataset.iloc[761,:].values)


print("\nUltimas ranks - Alunos Baixo Risco")
print(dataset.iloc[650,:].values)
print(dataset.iloc[63,:].values)
print(dataset.iloc[198,:].values)
print(dataset.iloc[60,:].values)

[Nota Pt., Nota Mat., Autoaval., Notas, Envol.Score]
[ 2.  2.  2.  1. 12.  0.]
[ 3.  3.  1.  1. 12.  0.]
[ 2.  3.  2.  2. 11.  0.]
[ 3.  2.  2.  1. 13.  0.]
[ 3.  2.  2.  1. 15.  0.]

Ultimas ranks - Alunos Baixo Risco
[ 5.  5.  5.  5. 25.  3.]
[ 5.  5.  5.  5. 25.  3.]
[ 5.  5.  5.  5. 25.  3.]
[ 5.  5.  5.  5. 25.  3.]
