In [59]:
import numpy as np
import pandas as pd


In [60]:
# Step 1: Load the dataset
import pickle
dataset = pd.read_pickle('dataset_final.pkl')

In [61]:
#TOPSIS normalization based
normalized_matrix = dataset.values / np.sqrt(np.sum(dataset.values ** 2, axis=0))

print(normalized_matrix)

[[0.03672044 0.03603165 0.03519349 0.0458259  0.03646108 0.0182696 ]
 [0.02754033 0.02702374 0.02639512 0.03436943 0.03993356 0.0182696 ]
 [0.02754033 0.03603165 0.03519349 0.03436943 0.0329886  0.0182696 ]
 ...
 [0.04590054 0.04503956 0.03519349 0.03436943 0.04166981 0.05480881]
 [0.04590054 0.04503956 0.04399186 0.03436943 0.03993356 0.05480881]
 [0.02754033 0.02702374 0.03519349 0.03436943 0.03125236 0.0182696 ]]


In [62]:
#AHP weight vector
weight_vector = [0.33067549, 0.33067549, 0.03620916, 0.09367133, 0.03620916,
       0.17255938]

weight_vector

[0.33067549, 0.33067549, 0.03620916, 0.09367133, 0.03620916, 0.17255938]

In [ ]:
#Tipical TOPSIS aproach

In [63]:
weighted_normalized_matrix = normalized_matrix * weight_vector

print(weighted_normalized_matrix)

[[0.01214255 0.01191478 0.00127433 0.00429257 0.00132023 0.00315259]
 [0.00910691 0.00893609 0.00095575 0.00321943 0.00144596 0.00315259]
 [0.00910691 0.01191478 0.00127433 0.00321943 0.00119449 0.00315259]
 ...
 [0.01517818 0.01489348 0.00127433 0.00321943 0.00150883 0.00945777]
 [0.01517818 0.01489348 0.00159291 0.00321943 0.00144596 0.00945777]
 [0.00910691 0.00893609 0.00127433 0.00321943 0.00113162 0.00315259]]


In [64]:
impacts = ['-', '-', '-', '-', '-','-',]

In [65]:
# Step 6: Determine the ideal and negative-ideal solutions
ideal_solution = np.empty(normalized_matrix.shape[1])
negative_ideal_solution = np.empty(normalized_matrix.shape[1])

for i in range(normalized_matrix.shape[1]):
    if impacts[i] == '+':
        ideal_solution[i] = np.max(weighted_normalized_matrix[:, i])
        negative_ideal_solution[i] = np.min(weighted_normalized_matrix[:, i])
    else:
        ideal_solution[i] = np.min(weighted_normalized_matrix[:, i])
        negative_ideal_solution[i] = np.max(weighted_normalized_matrix[:, i])


print(ideal_solution)
print(negative_ideal_solution)

[0.00607127 0.00595739 0.00031858 0.00107314 0.00031434 0.        ]
[0.01517818 0.01489348 0.00159291 0.00536572 0.0015717  0.00945777]


In [66]:
# Step 7: Calculate the Euclidean distances from the ideal and negative-ideal solutions
distance_to_ideal = np.sqrt(np.sum((weighted_normalized_matrix - ideal_solution) ** 2, axis=1))
distance_to_negative_ideal = np.sqrt(np.sum((weighted_normalized_matrix - negative_ideal_solution) ** 2, axis=1))

print(distance_to_ideal)
print(distance_to_negative_ideal)

[0.00972521 0.0058583  0.00780635 0.00755588 0.01322616 0.01088648
 0.00971301 0.0109182  0.00588972 0.01611676 0.01607259 0.00687379
 0.00825918 0.01068798 0.01087631 0.00785172 0.00334185 0.00485577
 0.01087631 0.01093064 0.00778115 0.01608635 0.00339219 0.00935544
 0.00487526 0.0095383  0.00967813 0.01074485 0.00391206 0.00457466
 0.01087631 0.00756398 0.00446324 0.00941784 0.00456298 0.0126644
 0.00685351 0.01076539 0.01093064 0.01274249 0.01460841 0.00587864
 0.00938736 0.00489928 0.01089211 0.01089809 0.00936557 0.00938201
 0.00779738 0.01090444 0.01610403 0.00486512 0.01301197 0.01074485
 0.01072129 0.01088648 0.01629442 0.00591876 0.01652141 0.00594973
 0.01654902 0.01626836 0.00958632 0.01654902 0.00452582 0.00782986
 0.01461288 0.00459044 0.00958632 0.01485393 0.01628617 0.00823646
 0.01090444 0.00959271 0.00776691 0.01626836 0.01089809 0.00487526
 0.0148234  0.01612608 0.00585843 0.00508096 0.00779951 0.01654436
 0.00821022 0.00818249 0.01088122 0.00588972 0.01480859 0.01087

In [67]:
# Step 8: Calculate the relative closeness to the ideal solution
closeness = distance_to_negative_ideal / (distance_to_ideal + distance_to_negative_ideal)

print(closeness)

[0.44161665 0.64880775 0.54905301 0.56505615 0.24921677 0.34484007
 0.44209087 0.34384294 0.64731018 0.11769849 0.12171248 0.63737331
 0.52985332 0.36895655 0.34537731 0.54747842 0.81520365 0.72695497
 0.34537731 0.34335883 0.55021056 0.1195536  0.81549112 0.46427608
 0.72608364 0.44810423 0.44595032 0.36609964 0.78787429 0.74161952
 0.34537731 0.56474732 0.75070364 0.4615043  0.74213753 0.30033946
 0.63849406 0.36549374 0.34335883 0.27880043 0.20323487 0.64776707
 0.46272395 0.72504373 0.34460093 0.34438159 0.46376734 0.46395443
 0.5496082  0.34418211 0.11873817 0.72653297 0.26806437 0.36609964
 0.36699015 0.34484007 0.06218647 0.64619167 0.02594555 0.64489296
 0.         0.0652286  0.44577441 0.         0.74405945 0.54816206
 0.203024   0.74105135 0.44577441 0.17672248 0.06338791 0.52934468
 0.34418211 0.4455359  0.55079315 0.0652286  0.34438159 0.72608364
 0.17844682 0.1174608  0.64862926 0.7141984  0.54934036 0.00378557
 0.53153835 0.53286152 0.34509889 0.64731018 0.17884475 0.3453

In [68]:
# Step 9: Rank the alternatives based on the relative closeness
ranked_indices = np.argsort(closeness)[::-1]  # Sort in descending order

# Step 10: Print the ranked alternatives
for i, idx in enumerate(ranked_indices):
    print(f"Rank {i+1}: AlunoId {idx+1}")

Rank 1: AlunoId 496
Rank 2: AlunoId 248
Rank 3: AlunoId 259
Rank 4: AlunoId 113
Rank 5: AlunoId 800
Rank 6: AlunoId 492
Rank 7: AlunoId 112
Rank 8: AlunoId 292
Rank 9: AlunoId 540
Rank 10: AlunoId 446
Rank 11: AlunoId 361
Rank 12: AlunoId 170
Rank 13: AlunoId 250
Rank 14: AlunoId 814
Rank 15: AlunoId 163
Rank 16: AlunoId 493
Rank 17: AlunoId 281
Rank 18: AlunoId 114
Rank 19: AlunoId 500
Rank 20: AlunoId 544
Rank 21: AlunoId 467
Rank 22: AlunoId 488
Rank 23: AlunoId 444
Rank 24: AlunoId 468
Rank 25: AlunoId 382
Rank 26: AlunoId 249
Rank 27: AlunoId 561
Rank 28: AlunoId 350
Rank 29: AlunoId 542
Rank 30: AlunoId 436
Rank 31: AlunoId 762
Rank 32: AlunoId 336
Rank 33: AlunoId 497
Rank 34: AlunoId 453
Rank 35: AlunoId 167
Rank 36: AlunoId 494
Rank 37: AlunoId 188
Rank 38: AlunoId 356
Rank 39: AlunoId 838
Rank 40: AlunoId 353
Rank 41: AlunoId 699
Rank 42: AlunoId 365
Rank 43: AlunoId 23
Rank 44: AlunoId 620
Rank 45: AlunoId 17
Rank 46: AlunoId 358
Rank 47: AlunoId 363
Rank 48: AlunoId 808
Ran

In [ ]:
print("[Nota Pt., Nota Mat., Autoaval., Notas, Envol.Score]")
print(dataset.iloc[495,:].values)
print(dataset.iloc[247,:].values)
print(dataset.iloc[258,:].values)
print(dataset.iloc[112,:].values)
print(dataset.iloc[491,:].values)
print(dataset.iloc[799,:].values)
print(dataset.iloc[111,:].values)

print("\nUltimas ranks - Alunos Baixo Risco")
print(dataset.iloc[63,:].values)
print(dataset.iloc[650,:].values)
print(dataset.iloc[60,:].values)
print(dataset.iloc[742,:].values)