In [2]:
import numpy as np
import pandas as pd

In [3]:
dataset = pd.read_pickle('dataset_final.pkl')

In [4]:
weights = [0.17202511458634429, 0.17133341698997043, 0.17064949815892275, 0.17024725535006752, 0.17280566459135063,  0.1429390503233443]

In [5]:
normalized_matrix = dataset.values / np.sqrt(np.sum(dataset.values ** 2, axis=0))


print(normalized_matrix)

[[0.03672044 0.03603165 0.03519349 0.0458259  0.03646108 0.0182696 ]
 [0.02754033 0.02702374 0.02639512 0.03436943 0.03993356 0.0182696 ]
 [0.02754033 0.03603165 0.03519349 0.03436943 0.0329886  0.0182696 ]
 ...
 [0.04590054 0.04503956 0.03519349 0.03436943 0.04166981 0.05480881]
 [0.04590054 0.04503956 0.04399186 0.03436943 0.03993356 0.05480881]
 [0.02754033 0.02702374 0.03519349 0.03436943 0.03125236 0.0182696 ]]


In [6]:
# Step 5: Calculate the weighted normalized decision matrix
weighted_normalized_matrix = normalized_matrix * weights

print(weighted_normalized_matrix)

[[0.00631684 0.00617343 0.00600575 0.00780173 0.00630068 0.00261144]
 [0.00473763 0.00463007 0.00450431 0.0058513  0.00690075 0.00261144]
 [0.00473763 0.00617343 0.00600575 0.0058513  0.00570062 0.00261144]
 ...
 [0.00789605 0.00771678 0.00600575 0.0058513  0.00720078 0.00783432]
 [0.00789605 0.00771678 0.00750719 0.0058513  0.00690075 0.00783432]
 [0.00473763 0.00463007 0.00600575 0.0058513  0.00540058 0.00261144]]


In [7]:
impacts = ['-', '-', '-', '-', '-','-',]

In [8]:
# Step 6: Determine the ideal and negative-ideal solutions
ideal_solution = np.empty(6)
negative_ideal_solution = np.empty(6)

for i in range(6):
    if impacts[i] == '+':
        ideal_solution[i] = np.max(weighted_normalized_matrix[:, i])
        negative_ideal_solution[i] = np.min(weighted_normalized_matrix[:, i])
    else:
        ideal_solution[i] = np.min(weighted_normalized_matrix[:, i])
        negative_ideal_solution[i] = np.max(weighted_normalized_matrix[:, i])


print(ideal_solution)
print(negative_ideal_solution)

[0.00315842 0.00308671 0.00150144 0.00195043 0.00150016 0.        ]
[0.00789605 0.00771678 0.00750719 0.00975217 0.00750081 0.00783432]


In [9]:
# Step 7: Calculate the Euclidean distances from the ideal and negative-ideal solutions
distance_to_ideal = np.sqrt(np.sum((weighted_normalized_matrix - ideal_solution) ** 2, axis=1))
distance_to_negative_ideal = np.sqrt(np.sum((weighted_normalized_matrix - negative_ideal_solution) ** 2, axis=1))

print(distance_to_ideal)
print(distance_to_negative_ideal)

[0.01019287 0.0080682  0.00848474 0.00720536 0.01331174 0.0101263
 0.00992438 0.01087636 0.00855668 0.01362759 0.01239869 0.00685617
 0.01118731 0.00851858 0.00987425 0.00936861 0.00493126 0.00632473
 0.00987425 0.01113927 0.007958   0.01279882 0.00733323 0.00795926
 0.00665756 0.00864653 0.00914362 0.01000206 0.00713879 0.00682735
 0.00987425 0.00739647 0.00681103 0.00947337 0.00664697 0.01116156
 0.00641289 0.01047378 0.01113927 0.01015776 0.01292751 0.00838129
 0.00875739 0.00702733 0.01026316 0.01040688 0.00822622 0.00865222
 0.0083121  0.01055717 0.01329559 0.00648635 0.01270166 0.01000206
 0.00940844 0.0101263  0.01430847 0.00897915 0.01474478 0.00943382
 0.01543383 0.0136309  0.00976709 0.01543383 0.00607865 0.00896452
 0.0130419  0.0070848  0.00976709 0.01346477 0.01409294 0.0096932
 0.01055717 0.00990892 0.0076347  0.0136309  0.01040688 0.00665756
 0.01411043 0.01387634 0.00805263 0.00841634 0.00834028 0.01531967
 0.01033402 0.00982037 0.00999656 0.00855668 0.0137518  0.009874

In [10]:
# Step 8: Calculate the relative closeness to the ideal solution
closeness = distance_to_negative_ideal / (distance_to_ideal + distance_to_negative_ideal)

print(closeness)

[0.38187361 0.51151063 0.47796268 0.56151987 0.18793024 0.35629983
 0.39347981 0.33179434 0.48524609 0.22457455 0.27992798 0.61257411
 0.37072982 0.47771952 0.36981699 0.44859762 0.70949519 0.62634983
 0.36981699 0.32096161 0.50539037 0.25360617 0.63160206 0.51137801
 0.61119126 0.45078727 0.48384766 0.41059192 0.60141079 0.6166506
 0.36981699 0.55388342 0.64327651 0.44163509 0.62409343 0.37371992
 0.63975603 0.39655415 0.32096161 0.37068222 0.25290457 0.49162481
 0.47160904 0.5958623  0.35024811 0.34473667 0.49783209 0.49809389
 0.49175469 0.33980601 0.23918395 0.61881073 0.26256579 0.41059192
 0.43253552 0.35629983 0.12481733 0.47355627 0.12467949 0.45654661
 0.         0.16126402 0.38867783 0.         0.65753778 0.4591497
 0.2481098  0.61137508 0.38867783 0.18568491 0.13978416 0.41583087
 0.33980601 0.38274662 0.51976776 0.16126402 0.34473667 0.61119126
 0.15099852 0.21943081 0.50500426 0.51038642 0.48464708 0.01920859
 0.3980077  0.42876374 0.36284195 0.48524609 0.16239151 0.369816

In [11]:
# Step 9: Rank the alternatives based on the relative closeness
ranked_indices = np.argsort(closeness)[::-1]  # Sort in descending order

# Step 10: Print the ranked alternatives
for i, idx in enumerate(ranked_indices):
    print(f"Rank {i+1}: AlunoId {idx+1}")

Rank 1: AlunoId 496
Rank 2: AlunoId 703
Rank 3: AlunoId 721
Rank 4: AlunoId 436
Rank 5: AlunoId 418
Rank 6: AlunoId 248
Rank 7: AlunoId 336
Rank 8: AlunoId 259
Rank 9: AlunoId 762
Rank 10: AlunoId 113
Rank 11: AlunoId 497
Rank 12: AlunoId 453
Rank 13: AlunoId 492
Rank 14: AlunoId 800
Rank 15: AlunoId 446
Rank 16: AlunoId 361
Rank 17: AlunoId 542
Rank 18: AlunoId 437
Rank 19: AlunoId 170
Rank 20: AlunoId 250
Rank 21: AlunoId 752
Rank 22: AlunoId 292
Rank 23: AlunoId 112
Rank 24: AlunoId 842
Rank 25: AlunoId 188
Rank 26: AlunoId 814
Rank 27: AlunoId 412
Rank 28: AlunoId 144
Rank 29: AlunoId 281
Rank 30: AlunoId 402
Rank 31: AlunoId 163
Rank 32: AlunoId 838
Rank 33: AlunoId 356
Rank 34: AlunoId 338
Rank 35: AlunoId 493
Rank 36: AlunoId 270
Rank 37: AlunoId 540
Rank 38: AlunoId 668
Rank 39: AlunoId 389
Rank 40: AlunoId 773
Rank 41: AlunoId 806
Rank 42: AlunoId 353
Rank 43: AlunoId 699
Rank 44: AlunoId 365
Rank 45: AlunoId 539
Rank 46: AlunoId 128
Rank 47: AlunoId 500
Rank 48: AlunoId 605
R

In [12]:
print("[Nota Pt., Nota Mat., Autoaval., Notas, Envol.Score]")
print(dataset.iloc[495,:].values)
print(dataset.iloc[247,:].values)
print(dataset.iloc[258,:].values)
print(dataset.iloc[112,:].values)
print(dataset.iloc[491,:].values)
print(dataset.iloc[799,:].values)
print(dataset.iloc[111,:].values)

print("\nUltimas ranks - Alunos Baixo Risco")
print(dataset.iloc[63,:].values)
print(dataset.iloc[650,:].values)
print(dataset.iloc[60,:].values)
print(dataset.iloc[742,:].values)

[Nota Pt., Nota Mat., Autoaval., Notas, Envol.Score]
[ 2.  2.  2.  1. 12.  0.]
[ 2.  2.  2.  1. 16.  0.]
[ 2.  2.  1.  1. 18.  0.]
[ 2.  2.  2.  1. 17.  0.]
[ 2.  2.  2.  1. 18.  0.]
[ 2.  2.  2.  1. 18.  0.]
[ 2.  2.  3.  1. 17.  0.]

Ultimas ranks - Alunos Baixo Risco
[ 5.  5.  5.  5. 25.  3.]
[ 5.  5.  5.  5. 25.  3.]
[ 5.  5.  5.  5. 25.  3.]
[ 5.  5.  5.  5. 25.  3.]
